/*  ═══════════════════════════════════════════════════════
    MAIN COMPETITIONS DATA — South India Focus
    Programming | Academic | Creative | Sports | Fitness
    ═══════════════════════════════════════════════════════ */
const MOCK_COMPETITIONS = [
    // ── Technical: Programming / Hackathons ──
    {
        id: "comp001",
        name: "CodeStorm Hackathon 2026",
        category: "Programming",
        skill: "Programming",
        date: "2026-07-18",
        time: "9:00 AM – 9:00 PM",
        deadline: "2026-07-10",
        location: "Bangalore, Karnataka",
        venue: "Indian Institute of Science (IISc), CV Raman Road, Bangalore 560012",
        organizer: "IISc Bangalore & Google Developer Groups",
        description: "A 12-hour national-level hackathon for college students. Build innovative solutions using any tech stack. Top 3 teams win cash prizes and internship opportunities at Google and Microsoft. Mentors from top tech companies available on-site.",
        prize: "₹2,00,000",
        eligibility: "College students (B.Tech / B.E / MCA)",
        team_size: "2–4 members",
        phone: "+91 80 2293 2000",
        email: "codestorm@iisc.ac.in",
        website: "https://www.interviewbit.com",
        coords: { lat: 13.0219, lng: 77.5671 }
    },
    {
        id: "comp002",
        name: "AP State Coding Championship",
        category: "Programming",
        skill: "Programming",
        date: "2026-08-05",
        time: "10:00 AM – 5:00 PM",
        deadline: "2026-07-28",
        location: "Vijayawada, Andhra Pradesh",
        venue: "SRM University AP, Neerukonda, Guntur District",
        organizer: "SRM AP & AP State IT Department",
        description: "State-level competitive programming contest with algorithmic challenges. 3 rounds: online qualifier, semi-final, and on-site grand final. Winners represent AP at national-level contests.",
        prize: "₹1,50,000",
        eligibility: "Open to all (students & professionals)",
        team_size: "Individual",
        phone: "+91 86322 17000",
        email: "coding@srmap.edu.in",
        website: "https://srmap.edu.in",
        coords: { lat: 16.4838, lng: 80.5010 }
    },
    {
        id: "comp003",
        name: "Deep Learning Challenge 2026",
        category: "Machine Learning",
        skill: "Machine Learning",
        date: "2026-09-12",
        time: "10:00 AM – 6:00 PM",
        deadline: "2026-09-01",
        location: "Chennai, Tamil Nadu",
        venue: "IIT Madras Research Park, Taramani, Chennai 600113",
        organizer: "IIT Madras AI Lab & NVIDIA",
        description: "Build and deploy deep learning models to solve real-world problems in healthcare, agriculture, and climate. Access to NVIDIA GPUs and mentorship from IIT Madras faculty. Published papers for top solutions.",
        prize: "₹3,00,000",
        eligibility: "B.Tech / M.Tech / PhD students",
        team_size: "1–3 members",
        phone: "+91 44 2257 8000",
        email: "dlchallenge@iitm.ac.in",
        website: "https://www.deeplearning.ai",
        coords: { lat: 12.9916, lng: 80.2336 }
    },
    {
        id: "comp004",
        name: "AI Innovation Summit & Hackathon",
        category: "Artificial Intelligence",
        skill: "Artificial Intelligence",
        date: "2026-10-20",
        time: "9:00 AM – 8:00 PM",
        deadline: "2026-10-10",
        location: "Hyderabad, Telangana",
        venue: "IIIT Hyderabad, Gachibowli, Hyderabad 500032",
        organizer: "IIIT Hyderabad & Microsoft Research India",
        description: "24-hour AI hackathon + summit with talks by industry leaders. Build AI solutions for social good. Access to Azure AI services. Best projects get incubation support at T-Hub.",
        prize: "₹5,00,000",
        eligibility: "Students & early-stage startups",
        team_size: "2–5 members",
        phone: "+91 40 6653 1000",
        email: "ai-summit@iiit.ac.in",
        website: "https://www.kaggle.com⁠",
        coords: { lat: 17.4455, lng: 78.3489 }
    },
    {
        id: "comp005",
        name: "DataViz Championship",
        category: "Data Science",
        skill: "Data Science",
        date: "2026-08-22",
        time: "10:00 AM – 4:00 PM",
        deadline: "2026-08-15",
        location: "Mysore, Karnataka",
        venue: "JSS Science & Technology University, Mysuru 570006",
        organizer: "JSS University & Tableau India",
        description: "Data visualization and storytelling competition. Participants analyze real datasets and present insights using Tableau, Power BI, or Python. Best dashboards win prizes and Tableau certifications.",
        prize: "₹75,000",
        eligibility: "College students",
        team_size: "1–2 members",
        phone: "+91 821 254 8200",
        email: "dataviz@jssstuniv.in",
        website: "https://www.ibm.com/",
        coords: { lat: 12.3113, lng: 76.6526 }
    },

    // ── Academic ──
    {
        id: "comp006",
        name: "South India Inter-College Quiz Fiesta",
        category: "Quiz",
        skill: "Quiz",
        date: "2026-07-25",
        time: "10:00 AM – 3:00 PM",
        deadline: "2026-07-18",
        location: "Coimbatore, Tamil Nadu",
        venue: "PSG College of Technology, Peelamedu, Coimbatore 641004",
        organizer: "PSG Tech & The Hindu Quiz Club",
        description: "Inter-college general knowledge quiz with prelims, semis, and finals. Topics: science, history, sports, entertainment, current affairs. Cash prizes and trophies for top 3 teams.",
        prize: "₹50,000",
        eligibility: "College students (UG & PG)",
        team_size: "2 members",
        phone: "+91 422 257 2177",
        email: "quizfest@psgtech.ac.in",
        website: "https://quizizz.com",
        coords: { lat: 11.0239, lng: 77.0026 }
    },
    {
        id: "comp007",
        name: "AP State Debate Championship",
        category: "Debate",
        skill: "Debate",
        date: "2026-09-05",
        time: "9:30 AM – 5:00 PM",
        deadline: "2026-08-25",
        location: "Tirupati, Andhra Pradesh",
        venue: "Sri Venkateswara University, Tirupati 517502",
        organizer: "SVU Literary Club & AP Education Department",
        description: "State-level debate competition in English and Telugu. Topics on national policy, education reform, and social issues. District-level qualifiers followed by state finals.",
        prize: "₹40,000",
        eligibility: "Students (Class 9 to PG)",
        team_size: "Individual",
        phone: "+91 877 228 9555",
        email: "debate@svuniversity.ac.in",
        website: "https://live.speechdebateindia.com/",
        coords: { lat: 13.6288, lng: 79.4192 }
    },

    // ── Creative & Cultural ──
    {
        id: "comp008",
        name: "Nrityanjali National Dance Festival",
        category: "Dance",
        skill: "Dance",
        date: "2026-08-15",
        time: "10:00 AM – 8:00 PM",
        deadline: "2026-08-01",
        location: "Hyderabad, Telangana",
        venue: "Ravindra Bharathi Auditorium, Nampally, Hyderabad 500001",
        organizer: "Telangana Cultural Academy & Doordarshan Hyderabad",
        description: "Grand national dance festival featuring Bharatanatyam, Kuchipudi, Kathak, and contemporary dance. Group and solo categories. Judges include renowned dance gurus. Performances telecast on DD National.",
        prize: "₹1,00,000",
        eligibility: "Age 8+, all skill levels",
        team_size: "Solo or Group (up to 10)",
        phone: "+91 40 2323 1789",
        email: "nrityanjali@tculturalacademy.in",
        website: "https://nrityanjalidance.com/",
        coords: { lat: 17.3897, lng: 78.4789 }
    },
    {
        id: "comp009",
        name: "Indian Raga",
        category: "Dance",
        skill: "Dance",
        date: "2026-07-28",
        time: "4:00 PM – 9:00 PM",
        deadline: "2026-07-20",
        location: "Ongole, Andhra Pradesh",
        venue: "Prakasam District Cultural Centre, Trunk Road, Ongole 523001",
        organizer: "Ongole Youth Cultural Association",
        description: "District-level dance competition open to all dance forms: classical, folk, freestyle, and Bollywood. Solo and group categories. Winners qualify for state-level competition.",
        prize: "₹25,000",
        eligibility: "Age 10+",
        team_size: "Solo or Group (up to 8)",
        phone: "+91 98765 11222",
        email: "ongole.dancestar@gmail.com",
        website: "https://nrityanjalidance.com/",
        coords: { lat: 15.5057, lng: 80.0499 }
    },
    {
        id: "comp010",
        name: "Sangeetham Music Festival",
        category: "Music",
        skill: "Music",
        date: "2026-12-15",
        time: "5:00 PM – 10:00 PM",
        deadline: "2026-11-30",
        location: "Chennai, Tamil Nadu",
        venue: "The Music Academy, TTK Road, Royapettah, Chennai 600014",
        organizer: "The Music Academy Chennai",
        description: "Prestigious annual Carnatic music festival. Competitions in vocal, veena, violin, mridangam, and flute. Winners perform at the December Music Season concerts. Scholarships for young musicians.",
        prize: "₹1,50,000",
        eligibility: "Age 12+, minimum 3 years training",
        team_size: "Individual",
        phone: "+91 44 2811 2231",
        email: "sangeetham@musicacademy.in",
        website: "https://www.singdilse.com/",
        coords: { lat: 13.0420, lng: 80.2608 }
    },
    {
        id: "comp011",
        name: "Sur Sangam Singing Competition",
        category: "Singing",
        skill: "Singing",
        date: "2026-09-20",
        time: "3:00 PM – 8:00 PM",
        deadline: "2026-09-10",
        location: "Kochi, Kerala",
        venue: "Kerala Fine Arts Hall, MG Road, Kochi 682016",
        organizer: "Kerala Sangeetha Nataka Akademi",
        description: "Open singing competition across genres: classical, semi-classical, Bollywood, and ghazals. Performance judged by film industry professionals. Winner gets a recording contract with a leading South Indian music label.",
        prize: "₹80,000",
        eligibility: "Age 15+",
        team_size: "Individual",
        phone: "+91 484 236 7800",
        email: "sursangam@keralasna.gov.in",
        website: "https://www.singdilse.com/",
        coords: { lat: 9.9816, lng: 76.2999 }
    },
    {
        id: "comp012",
        name: "Rangabhoomi Drama Festival",
        category: "Drama",
        skill: "Drama",
        date: "2026-10-05",
        time: "6:00 PM – 10:00 PM",
        deadline: "2026-09-20",
        location: "Mangalore, Karnataka",
        venue: "Town Hall, Lalbagh, Mangaluru 575003",
        organizer: "Karnataka Nataka Academy",
        description: "State-level one-act play competition. Plays in Kannada, Telugu, and English. Categories: comedy, tragedy, social drama. Esteemed theatre directors on the jury panel. Best play wins state tour opportunity.",
        prize: "₹60,000",
        eligibility: "Theatre groups (amateur & professional)",
        team_size: "5–15 members",
        phone: "+91 824 244 2920",
        email: "rangabhoomi@knacademy.org",
        website: "https://www.artdash.org/junior",
        coords: { lat: 12.8714, lng: 74.8428 }
    },
    {
        id: "comp013",
        name: "Lens & Light Photography Contest",
        category: "Photography",
        skill: "Photography",
        date: "2026-08-10",
        time: "All day (online submission)",
        deadline: "2026-08-05",
        location: "Online + Exhibition in Bangalore",
        venue: "National Gallery of Modern Art, Palace Road, Bangalore 560052",
        organizer: "Bangalore Photography Club & Canon India",
        description: "Theme-based photography contest. Monthly themes: Nature, Street Life, Portraits, Architecture. Shortlisted photos exhibited at NGMA Bangalore. Canon camera gear prizes for winners.",
        prize: "₹1,00,000 (+ Canon gear)",
        eligibility: "Open to all (amateur & professional)",
        team_size: "Individual",
        phone: "+91 80 2234 2338",
        email: "lensandlight@bpcblr.com",
        website: "https://photocontestdeadlines.com/all-photo-competitions/",
        coords: { lat: 12.9789, lng: 77.5918 }
    },
    {
        id: "comp014",
        name: "Chitrakala Art Olympiad",
        category: "Painting",
        skill: "Painting",
        date: "2026-11-08",
        time: "9:00 AM – 1:00 PM",
        deadline: "2026-10-25",
        location: "Trivandrum, Kerala",
        venue: "College of Fine Arts, Trivandrum, Kerala 695014",
        organizer: "Kerala Lalithakala Akademi",
        description: "State-level art competition across mediums: watercolor, oil, acrylic, and sketching. Age categories: juniors (8–14), seniors (15+), and open. Exhibition of all submitted works for one week.",
        prize: "₹45,000",
        eligibility: "Age 8+",
        team_size: "Individual",
        phone: "+91 471 233 4300",
        email: "chitrakala@keralalka.org",
        website: "https://calendarforartists.com/",
        coords: { lat: 8.5241, lng: 76.9366 }
    },

    // ── Sports ──
    {
        id: "comp015",
        name: "Prakasam District Premier League (Cricket)",
        category: "Cricket",
        skill: "Cricket",
        date: "2026-06-20",
        time: "7:00 AM – 6:00 PM",
        deadline: "2026-06-10",
        location: "Ongole, Andhra Pradesh",
        venue: "Ongole Municipal Cricket Ground, Stadium Road, Ongole 523001",
        organizer: "Prakasam District Cricket Association (PDCA)",
        description: "District-level T20 cricket tournament. 16 teams compete over 3 weekends. BCCI-certified umpires. Top performers scouted for Ranji Trophy trials. Live streaming on YouTube.",
        prize: "₹2,00,000",
        eligibility: "Registered cricket clubs in Prakasam district",
        team_size: "15-member squad",
        phone: "+91 99885 44321",
        email: "pdca.ongole@gmail.com",
        website: "https://www.espncricinfo.com",
        coords: { lat: 15.5050, lng: 80.0475 }
    },
    {
        id: "comp016",
        name: "South Zone Inter-College Cricket Trophy",
        category: "Cricket",
        skill: "Cricket",
        date: "2026-09-15",
        time: "8:00 AM – 5:00 PM",
        deadline: "2026-09-01",
        location: "Chennai, Tamil Nadu",
        venue: "MA Chidambaram Stadium (Chepauk), Chennai 600005",
        organizer: "TNCA & Sports Authority of India",
        description: "Inter-college cricket tournament for South Indian universities. 50-over format. State-level qualifiers followed by zonal finals at Chepauk. Scouts from IPL franchises attend finals.",
        prize: "₹3,00,000",
        eligibility: "College cricket teams (South India)",
        team_size: "16-member squad",
        phone: "+91 44 2536 1474",
        email: "southzone@tnca.org",
        website: "https://www.nclindia.in",
        coords: { lat: 13.0627, lng: 80.2792 }
    },
    {
        id: "comp017",
        name: "Kick Masters Football Tournament",
        category: "Football",
        skill: "Football",
        date: "2026-08-01",
        time: "6:00 AM – 6:00 PM",
        deadline: "2026-07-20",
        location: "Kochi, Kerala",
        venue: "Jawaharlal Nehru Stadium, Kaloor, Kochi 682017",
        organizer: "Kerala Football Association",
        description: "Open football tournament with 7-a-side and 11-a-side categories. Group stage + knockout format. International referees. Prize ceremony with Kerala Blasters FC players.",
        prize: "₹1,50,000",
        eligibility: "Registered football clubs / college teams",
        team_size: "7 or 11 + subs",
        phone: "+91 484 240 3456",
        email: "kickmasters@kfa.org.in",
        website: "https://globalcup.in",
        coords: { lat: 9.9897, lng: 76.2999 }
    },
    {
        id: "comp018",
        name: "Aqua Challenge Swimming Meet",
        category: "Swimming",
        skill: "Swimming",
        date: "2026-07-12",
        time: "7:00 AM – 1:00 PM",
        deadline: "2026-07-05",
        location: "Visakhapatnam, Andhra Pradesh",
        venue: "VMRDA Swimming Pool Complex, Beach Road, Vizag 530017",
        organizer: "AP Swimming Association & SAI",
        description: "State-level swimming meet with events: 50m, 100m, 200m freestyle, backstroke, butterfly, and relay. Age categories from 10 to open. SAI scouts present for national team selection.",
        prize: "₹60,000",
        eligibility: "Registered swimmers with district association",
        team_size: "Individual (relay: 4)",
        phone: "+91 891 278 4500",
        email: "aquachallenge@apswimming.in",
        website: "https://www.worldaquatics.com",
        coords: { lat: 17.7230, lng: 83.3198 }
    },
    {
        id: "comp019",
        name: "Dravida Martial Arts Championship",
        category: "Martial Arts",
        skill: "Martial Arts",
        date: "2026-10-10",
        time: "8:00 AM – 5:00 PM",
        deadline: "2026-09-25",
        location: "Madurai, Tamil Nadu",
        venue: "Tamukkam Grounds, Madurai 625020",
        organizer: "Tamil Nadu Martial Arts Federation",
        description: "Multi-discipline martial arts championship: Karate, Taekwondo, Judo, Silambam, and Kalaripayattu. Weight categories: light, middle, heavy. Demonstrations by martial arts masters.",
        prize: "₹80,000",
        eligibility: "Age 12+, any belt level",
        team_size: "Individual",
        phone: "+91 452 253 4200",
        email: "dravidama@tnmaf.org",
        website: "https://www.wkf.net/",
        coords: { lat: 9.9252, lng: 78.1198 }
    },

    // ── Fitness & Wellness ──
    {
        id: "comp020",
        name: "Yog Sports Foundation",
        category: "Yoga",
        skill: "Yoga",
        date: "2026-06-21",
        time: "5:30 AM – 10:00 AM",
        deadline: "2026-06-15",
        location: "Mysore, Karnataka",
        venue: "Mysore Palace Grounds, Mysuru 570001",
        organizer: "Mysore Yoga Heritage Foundation & Ministry of AYUSH",
        description: "Grand yoga event with competitive categories: Asana championship, Pranayama excellence, and Yoga therapy innovation. Thousands participate in the community yoga session. Live-streamed nationally.",
        prize: "₹50,000",
        eligibility: "Open to all",
        team_size: "Individual",
        phone: "+91 821 242 1111",
        email: "yogachallenge@mysoreheritage.org",
        website: "https://www.yogsportsfoundation.org",
        coords: { lat: 12.3052, lng: 76.6551 }
    },
    {
        id: "comp021",
        name: "Muscle Mania",
        category: "Fitness Training",
        skill: "Fitness Training",
        date: "2026-11-15",
        time: "7:00 AM – 4:00 PM",
        deadline: "2026-11-01",
        location: "Bangalore, Karnataka",
        venue: "Koramangala Indoor Stadium, Bangalore 560034",
        organizer: "CrossFit India & Under Armour",
        description: "South India's biggest CrossFit competition. Events: weighted runs, olympic lifts, gymnastics movements, endurance challenges. Scaled and RX divisions. Under Armour merchandise for all participants.",
        prize: "₹1,00,000",
        eligibility: "Age 18+, basic CrossFit experience",
        team_size: "Individual or Team of 3",
        phone: "+91 80 4112 3456",
        email: "crossfitopen@cfindial.com",
        website: "https://musclemania.com/india-tour-2026/",
        coords: { lat: 12.9352, lng: 77.6245 }
    }
]; module.exports = { MOCK_COMPETITIONS };
