/*  ═══════════════════════════════════════════════════════
    TECHNICAL ACADEMIES — 26 AP Districts
    ML | Data Science | Programming | AI
    ═══════════════════════════════════════════════════════ */
const TECH_ACADEMIES = [
// ─── 1. Srikakulam ───
{name:"Coursera — ML Academy",skill:"Machine Learning",rating:4.7,reviews_count:2200,address:"Srikakulam, Andhra Pradesh",phone:"",email:"",website:"https://www.coursera.org",description:"World-class ML courses from top universities. Access specializations in machine learning, deep learning, and AI from Stanford, Google, and more.",hours:["Online — 24/7"],location:{lat:18.2949,lng:83.8938},courses:["Machine Learning","Deep Learning","Neural Networks","ML Ops"],district:"Srikakulam",register:"https://www.coursera.org/join"},
{name:"Coursera — Data Science Academy",skill:"Data Science",rating:4.7,reviews_count:2200,address:"Srikakulam, Andhra Pradesh",phone:"",email:"",website:"https://www.coursera.org",description:"Data Science programs with IBM, Johns Hopkins, and Google. Hands-on projects and professional certificates.",hours:["Online — 24/7"],location:{lat:18.2949,lng:83.8938},courses:["Data Analysis","Python for DS","Statistics","SQL"],district:"Srikakulam",register:"https://www.coursera.org/join"},
{name:"edX — Programming Academy",skill:"Programming",rating:4.6,reviews_count:1800,address:"Srikakulam, Andhra Pradesh",phone:"",email:"",website:"https://www.edx.org",description:"Learn programming from Harvard, MIT, and top institutions. Free courses in Python, Java, C++, and web development.",hours:["Online — 24/7"],location:{lat:18.2949,lng:83.8938},courses:["Python","Java","C++","Web Development"],district:"Srikakulam",register:"https://auth.edx.org/register"},
{name:"NVIDIA Deep Learning Institute",skill:"Artificial Intelligence",rating:4.8,reviews_count:950,address:"Srikakulam, Andhra Pradesh",phone:"",email:"",website:"https://learn.nvidia.com",description:"Hands-on AI training with GPU-accelerated computing. Learn deep learning, computer vision, and NLP from NVIDIA experts.",hours:["Online — 24/7"],location:{lat:18.2949,lng:83.8938},courses:["Deep Learning","Computer Vision","NLP","GPU Computing"],district:"Srikakulam",register:"https://learn.nvidia.com/join"},

// ─── 2. Vizianagaram ───
{name:"Udemy — ML Academy",skill:"Machine Learning",rating:4.5,reviews_count:3500,address:"Vizianagaram, Andhra Pradesh",phone:"",email:"",website:"https://www.udemy.com",description:"Affordable ML courses with lifetime access. Learn from industry practitioners with hands-on projects and real datasets.",hours:["Online — 24/7"],location:{lat:18.1067,lng:83.3956},courses:["ML with Python","Scikit-Learn","TensorFlow","Data Preprocessing"],district:"Vizianagaram",register:"https://www.udemy.com/join/login-popup"},
{name:"Udemy — Data Science Academy",skill:"Data Science",rating:4.5,reviews_count:3500,address:"Vizianagaram, Andhra Pradesh",phone:"",email:"",website:"https://www.udemy.com",description:"Comprehensive data science bootcamps. From Python basics to advanced analytics, visualization, and machine learning.",hours:["Online — 24/7"],location:{lat:18.1067,lng:83.3956},courses:["Python for DS","Pandas","Matplotlib","Statistical Analysis"],district:"Vizianagaram",register:"https://www.udemy.com/join/login-popup"},
{name:"Codecademy — Programming Academy",skill:"Programming",rating:4.6,reviews_count:2100,address:"Vizianagaram, Andhra Pradesh",phone:"",email:"",website:"https://www.codecademy.com",description:"Interactive coding lessons. Learn by doing with instant feedback. Courses in Python, JavaScript, SQL, and more.",hours:["Online — 24/7"],location:{lat:18.1067,lng:83.3956},courses:["Python","JavaScript","SQL","React"],district:"Vizianagaram",register:"https://www.codecademy.com/register"},
{name:"Elements of AI",skill:"Artificial Intelligence",rating:4.7,reviews_count:800,address:"Vizianagaram, Andhra Pradesh",phone:"",email:"",website:"https://www.elementsofai.com",description:"Free AI course created by University of Helsinki & MinnaLearn. Understand what AI is and how it affects our lives.",hours:["Online — 24/7"],location:{lat:18.1067,lng:83.3956},courses:["AI Basics","Machine Learning Intro","Neural Networks","AI Ethics"],district:"Vizianagaram",register:"https://www.elementsofai.com/en/"},

// ─── 3. Visakhapatnam ───
{name:"Andhra University — ML Academy",skill:"Machine Learning",rating:4.4,reviews_count:450,address:"Waltair, Visakhapatnam, AP 530003",phone:"+91 891 284 4000",email:"",website:"https://www.andhrauniversity.edu.in",description:"One of the oldest universities in India offering ML and AI programs through the Department of Computer Science and Systems Engineering.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:17.7308,lng:83.3186},courses:["ML Fundamentals","Pattern Recognition","Data Mining","Statistical Learning"],district:"Visakhapatnam",register:"https://www.andhrauniversity.edu.in/admissions"},
{name:"Andhra University — Data Science",skill:"Data Science",rating:4.4,reviews_count:450,address:"Waltair, Visakhapatnam, AP 530003",phone:"+91 891 284 4000",email:"",website:"https://www.andhrauniversity.edu.in",description:"Data Science and Analytics programs with industry-relevant curriculum and research opportunities.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:17.7308,lng:83.3186},courses:["Data Analytics","Big Data","R Programming","Visualization"],district:"Visakhapatnam",register:"https://www.andhrauniversity.edu.in/admissions"},
{name:"HackerRank — Programming Academy",skill:"Programming",rating:4.7,reviews_count:5000,address:"Visakhapatnam, Andhra Pradesh",phone:"",email:"",website:"https://www.hackerrank.com",description:"Practice coding, prepare for interviews, and get hired. Challenges in algorithms, data structures, and AI.",hours:["Online — 24/7"],location:{lat:17.6868,lng:83.2185},courses:["Algorithms","Data Structures","Problem Solving","Interview Prep"],district:"Visakhapatnam",register:"https://www.hackerrank.com/auth/signup"},
{name:"DeepLearning.AI",skill:"Artificial Intelligence",rating:4.9,reviews_count:1200,address:"Visakhapatnam, Andhra Pradesh",phone:"",email:"",website:"https://www.deeplearning.ai",description:"Founded by Andrew Ng. World-class AI education with specializations in deep learning, NLP, and MLOps.",hours:["Online — 24/7"],location:{lat:17.6868,lng:83.2185},courses:["Deep Learning Specialization","NLP","GANs","MLOps"],district:"Visakhapatnam",register:"https://www.deeplearning.ai/signup"},

// ─── 4. Alluri Sitharama Raju ───
{name:"Great Learning — ML Academy",skill:"Machine Learning",rating:4.5,reviews_count:1600,address:"Alluri Sitharama Raju, AP",phone:"",email:"",website:"https://www.mygreatlearning.com",description:"Industry-aligned ML programs with mentorship from experts. Hands-on capstone projects and placement support.",hours:["Online — 24/7"],location:{lat:17.5,lng:82.1},courses:["ML Algorithms","Feature Engineering","Model Deployment","AutoML"],district:"Alluri Sitharama Raju",register:"https://www.mygreatlearning.com/signup"},
{name:"Great Learning — Data Science",skill:"Data Science",rating:4.5,reviews_count:1600,address:"Alluri Sitharama Raju, AP",phone:"",email:"",website:"https://www.mygreatlearning.com",description:"PG programs in Data Science with top university certificates. Learn analytics, ML, and business intelligence.",hours:["Online — 24/7"],location:{lat:17.5,lng:82.1},courses:["Data Analytics","Business Intelligence","Python","Tableau"],district:"Alluri Sitharama Raju",register:"https://www.mygreatlearning.com/signup"},
{name:"Kaggle — Programming Academy",skill:"Programming",rating:4.8,reviews_count:4000,address:"Alluri Sitharama Raju, AP",phone:"",email:"",website:"https://www.kaggle.com",description:"The world's largest data science community. Free courses, competitions, and datasets for hands-on learning.",hours:["Online — 24/7"],location:{lat:17.5,lng:82.1},courses:["Python","Data Manipulation","Visualization","ML Intro"],district:"Alluri Sitharama Raju",register:"https://www.kaggle.com/account/login"},
{name:"Databricks Academy",skill:"Artificial Intelligence",rating:4.6,reviews_count:700,address:"Alluri Sitharama Raju, AP",phone:"",email:"",website:"https://academy.databricks.com",description:"Learn data engineering, ML, and AI on the Databricks Lakehouse Platform. Free self-paced courses.",hours:["Online — 24/7"],location:{lat:17.5,lng:82.1},courses:["Data Engineering","MLflow","Spark ML","Lakehouse AI"],district:"Alluri Sitharama Raju",register:"https://academy.databricks.com/register"},

// ─── 5. Anakapalli ───
{name:"Simplilearn — ML Academy",skill:"Machine Learning",rating:4.4,reviews_count:1400,address:"Anakapalli, Andhra Pradesh",phone:"",email:"",website:"https://www.simplilearn.com",description:"Professional certification courses in ML, AI, and data science. Learn from industry experts with guaranteed certification.",hours:["Online — 24/7"],location:{lat:17.6910,lng:83.0037},courses:["ML Certification","Supervised Learning","Unsupervised Learning","Ensemble Methods"],district:"Anakapalli",register:"https://www.simplilearn.com/login"},
{name:"Simplilearn — Data Science",skill:"Data Science",rating:4.4,reviews_count:1400,address:"Anakapalli, Andhra Pradesh",phone:"",email:"",website:"https://www.simplilearn.com",description:"PG program in Data Science. Master Python, R, ML, and AI with capstone projects.",hours:["Online — 24/7"],location:{lat:17.6910,lng:83.0037},courses:["Data Science Bootcamp","Python","R","Power BI"],district:"Anakapalli",register:"https://www.simplilearn.com/login"},
{name:"freeCodeCamp — Programming",skill:"Programming",rating:4.8,reviews_count:6000,address:"Anakapalli, Andhra Pradesh",phone:"",email:"",website:"https://www.freecodecamp.org",description:"Free, self-paced coding curriculum. 3000+ hours of coursework. Earn certifications in web dev, data viz, and APIs.",hours:["Online — 24/7"],location:{lat:17.6910,lng:83.0037},courses:["HTML/CSS","JavaScript","React","Node.js"],district:"Anakapalli",register:"https://www.freecodecamp.org/signin"},
{name:"Google Cloud Skills Boost",skill:"Artificial Intelligence",rating:4.7,reviews_count:900,address:"Anakapalli, Andhra Pradesh",phone:"",email:"",website:"https://www.cloudskillsboost.google",description:"Hands-on labs for Google Cloud, AI, and ML. Earn badges and credentials recognized by industry.",hours:["Online — 24/7"],location:{lat:17.6910,lng:83.0037},courses:["Cloud AI","Vertex AI","BigQuery ML","TensorFlow on GCP"],district:"Anakapalli",register:"https://www.cloudskillsboost.google/users/sign_up"},

// ─── 6. Kakinada ───
{name:"JNTUK — ML Academy",skill:"Machine Learning",rating:4.3,reviews_count:380,address:"Kakinada, East Godavari, AP 533003",phone:"+91 884 230 0900",email:"",website:"https://www.jntuk.edu.in",description:"JNTU Kakinada offers ML and AI through CSE department. Research-focused with industry collaborations.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:16.9891,lng:82.2475},courses:["ML Theory","Neural Networks","Pattern Recognition","Research Methods"],district:"Kakinada",register:"https://www.jntuk.edu.in/admissions"},
{name:"JNTUK — Data Science",skill:"Data Science",rating:4.3,reviews_count:380,address:"Kakinada, East Godavari, AP 533003",phone:"+91 884 230 0900",email:"",website:"https://www.jntuk.edu.in",description:"Data Science programs at JNTUK with focus on analytics, big data, and statistical methods.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:16.9891,lng:82.2475},courses:["Big Data","Analytics","Statistical Methods","Data Warehousing"],district:"Kakinada",register:"https://www.jntuk.edu.in/admissions"},
{name:"GeeksforGeeks — Programming",skill:"Programming",rating:4.7,reviews_count:5500,address:"Kakinada, Andhra Pradesh",phone:"",email:"",website:"https://www.geeksforgeeks.org",description:"Practice coding problems, learn DSA, and prepare for tech interviews. Largest CS knowledge base.",hours:["Online — 24/7"],location:{lat:16.9891,lng:82.2475},courses:["DSA","Competitive Programming","System Design","Interview Prep"],district:"Kakinada",register:"https://auth.geeksforgeeks.org"},
{name:"JNTUK — AI Academy",skill:"Artificial Intelligence",rating:4.3,reviews_count:380,address:"Kakinada, East Godavari, AP 533003",phone:"+91 884 230 0900",email:"",website:"https://www.jntuk.edu.in",description:"AI and intelligent systems research and education at JNTU Kakinada's engineering departments.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:16.9891,lng:82.2475},courses:["AI Fundamentals","Expert Systems","Robotics","Computer Vision"],district:"Kakinada",register:"https://www.jntuk.edu.in/admissions"},

// ─── 7. East Godavari ───
{name:"Aditya Engineering College — ML",skill:"Machine Learning",rating:4.2,reviews_count:310,address:"Surampalem, East Godavari, AP",phone:"",email:"",website:"https://aec.edu.in",description:"ML programs at Aditya Engineering College with lab facilities and industry exposure.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:17.0,lng:81.8},courses:["ML Fundamentals","Python for ML","Deep Learning","Projects"],district:"East Godavari",register:"https://aec.edu.in/admissions"},
{name:"Aditya Engineering College — DS",skill:"Data Science",rating:4.2,reviews_count:310,address:"Surampalem, East Godavari, AP",phone:"",email:"",website:"https://aec.edu.in",description:"Data Science curriculum with practical analytics projects and placement support.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:17.0,lng:81.8},courses:["Data Analytics","Python","SQL","Tableau"],district:"East Godavari",register:"https://aec.edu.in/admissions"},
{name:"Scaler — Programming Academy",skill:"Programming",rating:4.6,reviews_count:1200,address:"East Godavari, Andhra Pradesh",phone:"",email:"",website:"https://www.scaler.com",description:"Structured DSA and system design courses taught by engineers from Google, Facebook, Amazon. High placement rate.",hours:["Online — 24/7"],location:{lat:17.0,lng:81.8},courses:["DSA","System Design","Full Stack","Backend Engineering"],district:"East Godavari",register:"https://www.scaler.com/apply"},
{name:"Fast.ai — AI Academy",skill:"Artificial Intelligence",rating:4.8,reviews_count:600,address:"East Godavari, Andhra Pradesh",phone:"",email:"",website:"https://www.fast.ai",description:"Free deep learning courses. Practical approach — make state-of-the-art models with minimal code.",hours:["Online — 24/7"],location:{lat:17.0,lng:81.8},courses:["Practical Deep Learning","NLP","Computer Vision","tabular ML"],district:"East Godavari",register:"https://course.fast.ai"},

// ─── 8. Konaseema ───
{name:"upGrad — ML Academy",skill:"Machine Learning",rating:4.5,reviews_count:900,address:"Konaseema, Andhra Pradesh",phone:"",email:"",website:"https://www.upgrad.com",description:"PG programs in ML from IIIT Bangalore and Liverpool John Moores. Industry projects and mentorship.",hours:["Online — 24/7"],location:{lat:16.7406,lng:81.6861},courses:["ML with Python","Deep Learning","NLP","Recommender Systems"],district:"Konaseema",register:"https://www.upgrad.com/register/"},
{name:"upGrad — Data Science",skill:"Data Science",rating:4.5,reviews_count:900,address:"Konaseema, Andhra Pradesh",phone:"",email:"",website:"https://www.upgrad.com",description:"Industry-relevant Data Science programs with university degrees and placement assistance.",hours:["Online — 24/7"],location:{lat:16.7406,lng:81.6861},courses:["Data Science Masters","Analytics","Big Data","Cloud"],district:"Konaseema",register:"https://www.upgrad.com/register/"},
{name:"Coding Ninjas — Programming",skill:"Programming",rating:4.5,reviews_count:1800,address:"Konaseema, Andhra Pradesh",phone:"",email:"",website:"https://www.codingninjas.com",description:"Structured coding courses with TA support. Learn DSA, web dev, and competitive programming.",hours:["Online — 24/7"],location:{lat:16.7406,lng:81.6861},courses:["DSA in Java","Web Development","Competitive Coding","Android Dev"],district:"Konaseema",register:"https://www.codingninjas.com/signup"},
{name:"DataRobot University",skill:"Artificial Intelligence",rating:4.5,reviews_count:400,address:"Konaseema, Andhra Pradesh",phone:"",email:"",website:"https://www.datarobot.com/learn",description:"Learn automated ML and AI engineering. Enterprise AI platform training and certification.",hours:["Online — 24/7"],location:{lat:16.7406,lng:81.6861},courses:["AutoML","AI Engineering","Time Series","MLOps"],district:"Konaseema",register:"https://www.datarobot.com/register"},

// ─── 9. Eluru ───
{name:"Sir C R Reddy College — ML",skill:"Machine Learning",rating:4.1,reviews_count:220,address:"Eluru, West Godavari, AP",phone:"",email:"",website:"https://www.sircrrcoe.ac.in",description:"ML programs at Sir C R Reddy College of Engineering with practical lab work and projects.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:16.7107,lng:81.0952},courses:["ML Basics","Regression","Classification","Clustering"],district:"Eluru",register:"https://www.sircrrcoe.ac.in/admissions"},
{name:"Sir C R Reddy College — DS",skill:"Data Science",rating:4.1,reviews_count:220,address:"Eluru, West Godavari, AP",phone:"",email:"",website:"https://www.sircrrcoe.ac.in",description:"Data Science and analytics training with focus on practical skills and industry readiness.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:16.7107,lng:81.0952},courses:["Data Analysis","Python","Excel Analytics","Visualization"],district:"Eluru",register:"https://www.sircrrcoe.ac.in/admissions"},
{name:"PrepInsta — Programming Academy",skill:"Programming",rating:4.3,reviews_count:1100,address:"Eluru, Andhra Pradesh",phone:"",email:"",website:"https://prepinsta.com",description:"Placement preparation with coding challenges, aptitude tests, and company-specific practice questions.",hours:["Online — 24/7"],location:{lat:16.7107,lng:81.0952},courses:["Aptitude","Coding Tests","TCS NQT Prep","Infosys Prep"],district:"Eluru",register:"https://prepinsta.com/login/"},
{name:"Amazon AWS Training",skill:"Artificial Intelligence",rating:4.6,reviews_count:1100,address:"Eluru, Andhra Pradesh",phone:"",email:"",website:"https://aws.amazon.com/training",description:"Free cloud and AI/ML training from Amazon. Learn SageMaker, Rekognition, and cloud-native AI services.",hours:["Online — 24/7"],location:{lat:16.7107,lng:81.0952},courses:["AWS ML","SageMaker","Cloud AI","Data Engineering"],district:"Eluru",register:"https://signin.aws.amazon.com"},

// ─── 10. West Godavari ───
{name:"Sasi Institute — ML Academy",skill:"Machine Learning",rating:4.2,reviews_count:260,address:"Tadepalligudem, West Godavari, AP",phone:"",email:"",website:"https://sasi.ac.in",description:"ML programs at Sasi Institute of Technology with modern labs and industry connections.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:16.9174,lng:81.3399},courses:["ML Fundamentals","Scikit-Learn","Deep Learning","Projects"],district:"West Godavari",register:"https://sasi.ac.in/admissions"},
{name:"Sasi Institute — Data Science",skill:"Data Science",rating:4.2,reviews_count:260,address:"Tadepalligudem, West Godavari, AP",phone:"",email:"",website:"https://sasi.ac.in",description:"Data Science coursework with analytics projects and industry internship opportunities.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:16.9174,lng:81.3399},courses:["Analytics","Python","R","Data Visualization"],district:"West Godavari",register:"https://sasi.ac.in/admissions"},
{name:"Internshala Trainings — Programming",skill:"Programming",rating:4.4,reviews_count:2000,address:"West Godavari, Andhra Pradesh",phone:"",email:"",website:"https://trainings.internshala.com",description:"Affordable self-paced training in programming, web development, and app development with internship guarantee.",hours:["Online — 24/7"],location:{lat:16.9174,lng:81.3399},courses:["Python","Web Dev","Android","Core Java"],district:"West Godavari",register:"https://internshala.com/login"},
{name:"Meta AI Learning",skill:"Artificial Intelligence",rating:4.5,reviews_count:500,address:"West Godavari, Andhra Pradesh",phone:"",email:"",website:"https://ai.meta.com/learn",description:"Learn AI from Meta's research team. Resources on PyTorch, LLMs, and responsible AI.",hours:["Online — 24/7"],location:{lat:16.9174,lng:81.3399},courses:["PyTorch","LLMs","Responsible AI","Computer Vision"],district:"West Godavari",register:"https://www.facebook.com/signup"},

// ─── 11. NTR District (Vijayawada) ───
{name:"SRM University AP — ML Academy",skill:"Machine Learning",rating:4.5,reviews_count:420,address:"Neerukonda, Guntur Dist, AP",phone:"+91 86322 17000",email:"",website:"https://srmap.edu.in",description:"SRM AP offers cutting-edge ML programs with world-class research facilities and international faculty.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:16.4838,lng:80.5010},courses:["ML Algorithms","Deep Learning","Reinforcement Learning","Research"],district:"NTR District",register:"https://applications.srmap.edu.in"},
{name:"SRM University AP — Data Science",skill:"Data Science",rating:4.5,reviews_count:420,address:"Neerukonda, Guntur Dist, AP",phone:"+91 86322 17000",email:"",website:"https://srmap.edu.in",description:"B.Tech and M.Tech in Data Science with state-of-the-art labs and industry partnerships.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:16.4838,lng:80.5010},courses:["Data Science","Big Data","Cloud Analytics","AI"],district:"NTR District",register:"https://applications.srmap.edu.in"},
{name:"LinkedIn Learning — Programming",skill:"Programming",rating:4.5,reviews_count:3000,address:"Vijayawada, Andhra Pradesh",phone:"",email:"",website:"https://www.linkedin.com/learning",description:"Professional programming courses taught by industry experts. Certificate recognized by employers worldwide.",hours:["Online — 24/7"],location:{lat:16.5062,lng:80.6480},courses:["Python","Java","JavaScript","Cloud Dev"],district:"NTR District",register:"https://www.linkedin.com/signup"},
{name:"SRM University AP — AI Academy",skill:"Artificial Intelligence",rating:4.5,reviews_count:420,address:"Neerukonda, Guntur Dist, AP",phone:"+91 86322 17000",email:"",website:"https://srmap.edu.in",description:"AI and robotics programs at SRM AP with dedicated research centers and innovation labs.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:16.4838,lng:80.5010},courses:["AI Fundamentals","Robotics","NLP","Computer Vision"],district:"NTR District",register:"https://applications.srmap.edu.in"},

// ─── 12. Krishna ───
{name:"KL University — ML Academy",skill:"Machine Learning",rating:4.4,reviews_count:550,address:"Green Fields, Vaddeswaram, Guntur, AP",phone:"",email:"",website:"https://www.kluniversity.in",description:"KL University offers specialized ML programs with industry-oriented curriculum and placement record.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:16.4419,lng:80.6219},courses:["ML Specialization","Deep Learning","NLP","Computer Vision"],district:"Krishna",register:"https://www.kluniversity.in/admissions"},
{name:"KL University — Data Science",skill:"Data Science",rating:4.4,reviews_count:550,address:"Green Fields, Vaddeswaram, Guntur, AP",phone:"",email:"",website:"https://www.kluniversity.in",description:"Data science programs with practical projects, hackathons, and industry mentorship at KLU.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:16.4419,lng:80.6219},courses:["Data Analytics","Python","R","Power BI"],district:"Krishna",register:"https://www.kluniversity.in/admissions"},
{name:"Skillshare — Programming Academy",skill:"Programming",rating:4.3,reviews_count:1500,address:"Krishna District, Andhra Pradesh",phone:"",email:"",website:"https://www.skillshare.com",description:"Creative and tech classes including programming, web design, and app development. Community-based learning.",hours:["Online — 24/7"],location:{lat:16.6100,lng:80.7214},courses:["Web Design","Python","JavaScript","UI/UX"],district:"Krishna",register:"https://www.skillshare.com/signup"},
{name:"OpenAI — AI Academy",skill:"Artificial Intelligence",rating:4.9,reviews_count:2000,address:"Krishna District, Andhra Pradesh",phone:"",email:"",website:"https://platform.openai.com",description:"Access OpenAI's API platform and learn to build AI applications using GPT, DALL-E, and Whisper.",hours:["Online — 24/7"],location:{lat:16.6100,lng:80.7214},courses:["GPT API","Prompt Engineering","AI Apps","Fine-tuning"],district:"Krishna",register:"https://platform.openai.com/signup"},

// ─── 13. Guntur ───
{name:"Vignan's University — ML Academy",skill:"Machine Learning",rating:4.3,reviews_count:400,address:"Vadlamudi, Guntur, AP",phone:"",email:"",website:"https://vignan.ac.in",description:"Vignan's FIST offers ML and AI programs with strong research output and industry collaborations.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:16.2335,lng:80.5560},courses:["ML Engineering","Deep Learning","Data Mining","Research"],district:"Guntur",register:"https://vignan.ac.in/admissions"},
{name:"Vignan's University — Data Science",skill:"Data Science",rating:4.3,reviews_count:400,address:"Vadlamudi, Guntur, AP",phone:"",email:"",website:"https://vignan.ac.in",description:"Data Science programs at Vignan's with practical analytics and emerging technology courses.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:16.2335,lng:80.5560},courses:["Data Analytics","Big Data","Cloud Computing","IoT"],district:"Guntur",register:"https://vignan.ac.in/admissions"},
{name:"Pluralsight — Programming Academy",skill:"Programming",rating:4.5,reviews_count:1800,address:"Guntur, Andhra Pradesh",phone:"",email:"",website:"https://www.pluralsight.com",description:"Tech skills platform with skill assessments, learning paths, and hands-on projects in all major programming languages.",hours:["Online — 24/7"],location:{lat:16.3067,lng:80.4365},courses:["C#","Python","Cloud Dev","DevOps"],district:"Guntur",register:"https://www.pluralsight.com/sign-up"},
{name:"Vignan's University — AI Academy",skill:"Artificial Intelligence",rating:4.3,reviews_count:400,address:"Vadlamudi, Guntur, AP",phone:"",email:"",website:"https://vignan.ac.in",description:"AI and intelligent systems programs at Vignan's with dedicated AI research center.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:16.2335,lng:80.5560},courses:["AI Fundamentals","Expert Systems","Neural Networks","Robotics"],district:"Guntur",register:"https://vignan.ac.in/admissions"},

// ─── 14–26 Remaining Districts (compact) ───
// 14. Palnadu
{name:"Coursera — ML Academy (Palnadu)",skill:"Machine Learning",rating:4.7,reviews_count:2200,address:"Palnadu, Andhra Pradesh",phone:"",email:"",website:"https://www.coursera.org",description:"World-class ML courses from Stanford, Google, and top universities available online.",hours:["Online — 24/7"],location:{lat:16.2316,lng:79.7424},courses:["ML Specialization","Deep Learning","TensorFlow","AI for Everyone"],district:"Palnadu",register:"https://www.coursera.org/join"},
{name:"Coursera — Data Science (Palnadu)",skill:"Data Science",rating:4.7,reviews_count:2200,address:"Palnadu, Andhra Pradesh",phone:"",email:"",website:"https://www.coursera.org",description:"IBM and Google Data Science professional certificates on Coursera.",hours:["Online — 24/7"],location:{lat:16.2316,lng:79.7424},courses:["IBM DS Certificate","Google DA","Python","SQL"],district:"Palnadu",register:"https://www.coursera.org/join"},
{name:"FutureLearn — Programming (Palnadu)",skill:"Programming",rating:4.4,reviews_count:900,address:"Palnadu, Andhra Pradesh",phone:"",email:"",website:"https://www.futurelearn.com",description:"UK-based platform with university-backed programming and tech courses.",hours:["Online — 24/7"],location:{lat:16.2316,lng:79.7424},courses:["Programming Basics","Web Dev","Cyber Security","Cloud"],district:"Palnadu",register:"https://www.futurelearn.com/register"},
{name:"FutureLearn — AI (Palnadu)",skill:"Artificial Intelligence",rating:4.4,reviews_count:900,address:"Palnadu, Andhra Pradesh",phone:"",email:"",website:"https://www.futurelearn.com/subjects/it-and-computer-science-courses",description:"AI and CS courses from leading UK universities on FutureLearn platform.",hours:["Online — 24/7"],location:{lat:16.2316,lng:79.7424},courses:["AI Intro","Machine Learning","Data Science","Robotics"],district:"Palnadu",register:"https://www.futurelearn.com/register"},

// 15. Bapatla
{name:"Bapatla Engineering College — ML",skill:"Machine Learning",rating:4.1,reviews_count:200,address:"Bapatla, Guntur Dist, AP",phone:"",email:"",website:"https://www.becbapatla.ac.in",description:"Government engineering college offering ML coursework through CSE department.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:15.9048,lng:80.4674},courses:["ML Basics","Python ML","Neural Networks","Projects"],district:"Bapatla",register:"https://www.becbapatla.ac.in/admissions"},
{name:"Bapatla Engineering College — DS",skill:"Data Science",rating:4.1,reviews_count:200,address:"Bapatla, Guntur Dist, AP",phone:"",email:"",website:"https://www.becbapatla.ac.in",description:"Data science and analytics training with industry-focused projects.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:15.9048,lng:80.4674},courses:["Data Analytics","Statistics","Python","R"],district:"Bapatla",register:"https://www.becbapatla.ac.in/admissions"},
{name:"Alison — Programming (Bapatla)",skill:"Programming",rating:4.2,reviews_count:800,address:"Bapatla, Andhra Pradesh",phone:"",email:"",website:"https://alison.com",description:"Free online courses with diploma certificates in programming and IT.",hours:["Online — 24/7"],location:{lat:15.9048,lng:80.4674},courses:["Python","JavaScript","HTML/CSS","Databases"],district:"Bapatla",register:"https://alison.com/register"},
{name:"Bapatla Engineering College — AI",skill:"Artificial Intelligence",rating:4.1,reviews_count:200,address:"Bapatla, Guntur Dist, AP",phone:"",email:"",website:"https://www.becbapatla.ac.in",description:"AI fundamentals and intelligent computing at Bapatla Engineering College.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:15.9048,lng:80.4674},courses:["AI Basics","Expert Systems","Fuzzy Logic","Neural Nets"],district:"Bapatla",register:"https://www.becbapatla.ac.in/admissions"},

// 16. Prakasam (Ongole)
{name:"PACE Institute — ML Academy",skill:"Machine Learning",rating:4.2,reviews_count:280,address:"Ongole, Prakasam, AP",phone:"",email:"",website:"https://pace.ac.in",description:"PACE Institute offers ML and AI programs with modern infrastructure in Ongole.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:15.5057,lng:80.0499},courses:["ML Fundamentals","Deep Learning","Python","Projects"],district:"Prakasam",register:"https://pace.ac.in/admissions"},
{name:"PACE Institute — Data Science",skill:"Data Science",rating:4.2,reviews_count:280,address:"Ongole, Prakasam, AP",phone:"",email:"",website:"https://pace.ac.in",description:"Data Science and analytics programs at PACE Institute of Technology and Sciences.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:15.5057,lng:80.0499},courses:["Data Analytics","Python","R","Tableau"],district:"Prakasam",register:"https://pace.ac.in/admissions"},
{name:"Udacity — Programming (Prakasam)",skill:"Programming",rating:4.5,reviews_count:1200,address:"Prakasam, Andhra Pradesh",phone:"",email:"",website:"https://www.udacity.com",description:"Nanodegree programs in programming, web development, and cloud engineering from industry leaders.",hours:["Online — 24/7"],location:{lat:15.5057,lng:80.0499},courses:["Full Stack","Cloud Dev","Data Engineering","React"],district:"Prakasam",register:"https://www.udacity.com/account/auth#!/signup"},
{name:"Intellipaat — AI (Prakasam)",skill:"Artificial Intelligence",rating:4.4,reviews_count:700,address:"Prakasam, Andhra Pradesh",phone:"",email:"",website:"https://intellipaat.com/ai-course-training",description:"AI and ML certification training with 24/7 support and hands-on projects.",hours:["Online — 24/7"],location:{lat:15.5057,lng:80.0499},courses:["AI Certification","Deep Learning","NLP","Computer Vision"],district:"Prakasam",register:"https://intellipaat.com/login"},

// 17. Nellore
{name:"VIT-AP University — ML",skill:"Machine Learning",rating:4.5,reviews_count:500,address:"Amaravati, Near Vijayawada, AP",phone:"",email:"",website:"https://vitap.ac.in",description:"VIT-AP offers world-class ML programs with international collaborations and research focus.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:14.4426,lng:79.9865},courses:["ML Engineering","Data Mining","Pattern Recognition","Research"],district:"Nellore",register:"https://admissions.vit.ac.in"},
{name:"VIT-AP University — DS",skill:"Data Science",rating:4.5,reviews_count:500,address:"Amaravati, Near Vijayawada, AP",phone:"",email:"",website:"https://vitap.ac.in",description:"Data Science specializations with cutting-edge curriculum at VIT-AP University.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:14.4426,lng:79.9865},courses:["Data Science","Analytics","AI","Cloud"],district:"Nellore",register:"https://admissions.vit.ac.in"},
{name:"Microsoft Learn — Programming",skill:"Programming",rating:4.7,reviews_count:4000,address:"Nellore, Andhra Pradesh",phone:"",email:"",website:"https://learn.microsoft.com",description:"Free modules and learning paths for Azure, .NET, Power Platform, and more from Microsoft.",hours:["Online — 24/7"],location:{lat:14.4426,lng:79.9865},courses:[".NET","Azure","Power Platform","C#"],district:"Nellore",register:"https://signup.live.com"},
{name:"Oracle AI University",skill:"Artificial Intelligence",rating:4.4,reviews_count:600,address:"Nellore, Andhra Pradesh",phone:"",email:"",website:"https://education.oracle.com",description:"Oracle-certified AI and cloud training. Enterprise-grade AI and ML certification programs.",hours:["Online — 24/7"],location:{lat:14.4426,lng:79.9865},courses:["Oracle AI","Cloud Infrastructure","Autonomous DB","Java AI"],district:"Nellore",register:"https://profile.oracle.com"},

// 18. Tirupati
{name:"SV University — ML Academy",skill:"Machine Learning",rating:4.3,reviews_count:350,address:"Tirupati, Chittoor Dist, AP 517502",phone:"",email:"",website:"https://svuniversity.edu.in",description:"Sri Venkateswara University offers ML and AI research programs through the CS department.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:13.6288,lng:79.4192},courses:["ML Research","Statistical Learning","Deep Learning","Data Mining"],district:"Tirupati",register:"https://svuniversity.edu.in/admissions"},
{name:"SV University — Data Science",skill:"Data Science",rating:4.3,reviews_count:350,address:"Tirupati, Chittoor Dist, AP 517502",phone:"",email:"",website:"https://svuniversity.edu.in",description:"Data Science and computational statistics programs at SVU.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:13.6288,lng:79.4192},courses:["Data Science","Statistics","R","Python"],district:"Tirupati",register:"https://svuniversity.edu.in/admissions"},
{name:"Oracle University — Programming",skill:"Programming",rating:4.4,reviews_count:600,address:"Tirupati, Andhra Pradesh",phone:"",email:"",website:"https://education.oracle.com",description:"Oracle-certified Java, database, and cloud programming courses with industry recognition.",hours:["Online — 24/7"],location:{lat:13.6288,lng:79.4192},courses:["Java","Oracle DB","PL/SQL","Cloud Dev"],district:"Tirupati",register:"https://profile.oracle.com"},
{name:"SV University — AI Academy",skill:"Artificial Intelligence",rating:4.3,reviews_count:350,address:"Tirupati, Chittoor Dist, AP 517502",phone:"",email:"",website:"https://svuniversity.edu.in",description:"AI and intelligent systems research at Sri Venkateswara University.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:13.6288,lng:79.4192},courses:["AI Fundamentals","Expert Systems","Computer Vision","NLP"],district:"Tirupati",register:"https://svuniversity.edu.in/admissions"},

// 19. Chittoor
{name:"MITS — ML Academy",skill:"Machine Learning",rating:4.2,reviews_count:240,address:"Madanapalle, Chittoor, AP",phone:"",email:"",website:"https://mits.ac.in",description:"Madanapalle Institute of Technology offers ML programs with industry-focused curriculum.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:13.2172,lng:79.1003},courses:["ML Basics","Python ML","Neural Networks","Projects"],district:"Chittoor",register:"https://mits.ac.in/admissions"},
{name:"MITS — Data Science",skill:"Data Science",rating:4.2,reviews_count:240,address:"Madanapalle, Chittoor, AP",phone:"",email:"",website:"https://mits.ac.in",description:"Data analytics and science programs at MITS with lab facilities.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:13.2172,lng:79.1003},courses:["Data Analytics","Python","SQL","Visualization"],district:"Chittoor",register:"https://mits.ac.in/admissions"},
{name:"IBM SkillsBuild — Programming",skill:"Programming",rating:4.5,reviews_count:1500,address:"Chittoor, Andhra Pradesh",phone:"",email:"",website:"https://skillsbuild.org",description:"Free learning platform from IBM. Courses in programming, cybersecurity, AI, and professional skills.",hours:["Online — 24/7"],location:{lat:13.2172,lng:79.1003},courses:["Python","Cloud","Cybersecurity","AI Basics"],district:"Chittoor",register:"https://skillsbuild.org/register"},
{name:"MITS — AI Academy",skill:"Artificial Intelligence",rating:4.2,reviews_count:240,address:"Madanapalle, Chittoor, AP",phone:"",email:"",website:"https://mits.ac.in",description:"AI and intelligent computing programs at Madanapalle Institute.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:13.2172,lng:79.1003},courses:["AI Fundamentals","Machine Learning","IoT","Robotics"],district:"Chittoor",register:"https://mits.ac.in/admissions"},

// 20. Annamayya
{name:"Udemy — ML Academy (Annamayya)",skill:"Machine Learning",rating:4.5,reviews_count:3500,address:"Annamayya, Andhra Pradesh",phone:"",email:"",website:"https://www.udemy.com",description:"Affordable ML courses with lifetime access and hands-on projects.",hours:["Online — 24/7"],location:{lat:14.6819,lng:78.5701},courses:["ML with Python","Deep Learning","TensorFlow","Kaggle"],district:"Annamayya",register:"https://www.udemy.com/join/login-popup"},
{name:"Udemy — Data Science (Annamayya)",skill:"Data Science",rating:4.5,reviews_count:3500,address:"Annamayya, Andhra Pradesh",phone:"",email:"",website:"https://www.udemy.com",description:"Complete data science bootcamps from basics to advanced analytics.",hours:["Online — 24/7"],location:{lat:14.6819,lng:78.5701},courses:["Python DS","Pandas","Matplotlib","Statistical Analysis"],district:"Annamayya",register:"https://www.udemy.com/join/login-popup"},
{name:"SoloLearn — Programming",skill:"Programming",rating:4.3,reviews_count:1000,address:"Annamayya, Andhra Pradesh",phone:"",email:"",website:"https://www.sololearn.com",description:"Learn coding on the go. Bite-sized lessons and a supportive community of learners.",hours:["Online — 24/7"],location:{lat:14.6819,lng:78.5701},courses:["Python","JavaScript","Java","C++"],district:"Annamayya",register:"https://www.sololearn.com/Profile/SignUp"},
{name:"Kaggle — AI Academy (Annamayya)",skill:"Artificial Intelligence",rating:4.8,reviews_count:4000,address:"Annamayya, Andhra Pradesh",phone:"",email:"",website:"https://www.kaggle.com/learn",description:"Free AI and ML micro-courses on Kaggle. Learn by doing with real datasets.",hours:["Online — 24/7"],location:{lat:14.6819,lng:78.5701},courses:["Intro to ML","Deep Learning","Feature Engineering","NLP"],district:"Annamayya",register:"https://www.kaggle.com/account/login"},

// 21. YSR Kadapa
{name:"AITS Kadapa — ML Academy",skill:"Machine Learning",rating:4.1,reviews_count:180,address:"Kadapa, YSR Dist, AP",phone:"",email:"",website:"https://www.aitskadapa.ac.in",description:"Annamacharya Institute offers ML programs with dedicated computing labs.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:14.4673,lng:78.8242},courses:["ML Fundamentals","Python","Deep Learning","Projects"],district:"YSR Kadapa",register:"https://www.aitskadapa.ac.in/admissions"},
{name:"AITS Kadapa — Data Science",skill:"Data Science",rating:4.1,reviews_count:180,address:"Kadapa, YSR Dist, AP",phone:"",email:"",website:"https://www.aitskadapa.ac.in",description:"Data science training at AITS Kadapa with practical analytics focus.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:14.4673,lng:78.8242},courses:["Data Analytics","Python","SQL","Visualization"],district:"YSR Kadapa",register:"https://www.aitskadapa.ac.in/admissions"},
{name:"W3Schools — Programming",skill:"Programming",rating:4.6,reviews_count:8000,address:"YSR Kadapa, Andhra Pradesh",phone:"",email:"",website:"https://www.w3schools.com",description:"The world's largest web developer reference. Free tutorials, examples, and exercises.",hours:["Online — 24/7"],location:{lat:14.4673,lng:78.8242},courses:["HTML","CSS","JavaScript","Python"],district:"YSR Kadapa",register:"https://profile.w3schools.com"},
{name:"AITS Kadapa — AI Academy",skill:"Artificial Intelligence",rating:4.1,reviews_count:180,address:"Kadapa, YSR Dist, AP",phone:"",email:"",website:"https://www.aitskadapa.ac.in",description:"AI and intelligent systems education at Annamacharya Institute.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:14.4673,lng:78.8242},courses:["AI Basics","Neural Networks","Expert Systems","IoT"],district:"YSR Kadapa",register:"https://www.aitskadapa.ac.in/admissions"},

// 22. Anantapuramu
{name:"JNTUA — ML Academy",skill:"Machine Learning",rating:4.3,reviews_count:380,address:"Anantapuramu, AP",phone:"",email:"",website:"https://www.jntua.ac.in",description:"JNTU Anantapur offers ML and AI programs with strong research focus.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:14.6819,lng:77.6006},courses:["ML Theory","Statistical Learning","Deep Learning","Research"],district:"Anantapuramu",register:"https://www.jntua.ac.in/admissions"},
{name:"JNTUA — Data Science",skill:"Data Science",rating:4.3,reviews_count:380,address:"Anantapuramu, AP",phone:"",email:"",website:"https://www.jntua.ac.in",description:"Data Science programs at JNTUA with computational statistics and analytics tracks.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:14.6819,lng:77.6006},courses:["Data Analytics","Big Data","Statistics","Python"],district:"Anantapuramu",register:"https://www.jntua.ac.in/admissions"},
{name:"DataCamp — Programming",skill:"Programming",rating:4.5,reviews_count:2500,address:"Anantapuramu, Andhra Pradesh",phone:"",email:"",website:"https://www.datacamp.com",description:"Interactive data science and programming courses. Learn R, Python, and SQL through hands-on exercises.",hours:["Online — 24/7"],location:{lat:14.6819,lng:77.6006},courses:["Python","R","SQL","Shell"],district:"Anantapuramu",register:"https://www.datacamp.com/users/sign_up"},
{name:"IBM AI Academy",skill:"Artificial Intelligence",rating:4.5,reviews_count:1500,address:"Anantapuramu, Andhra Pradesh",phone:"",email:"",website:"https://skillsbuild.org",description:"Free AI and tech courses from IBM SkillsBuild. Industry-recognized credentials.",hours:["Online — 24/7"],location:{lat:14.6819,lng:77.6006},courses:["AI Fundamentals","Watson AI","Cloud AI","Data Science"],district:"Anantapuramu",register:"https://skillsbuild.org/register"},

// 23. Sri Sathya Sai
{name:"Great Learning — ML (Sri Sathya Sai)",skill:"Machine Learning",rating:4.5,reviews_count:1600,address:"Sri Sathya Sai, Andhra Pradesh",phone:"",email:"",website:"https://www.mygreatlearning.com",description:"Industry-aligned ML programs with expert mentorship and career support.",hours:["Online — 24/7"],location:{lat:14.2,lng:77.61},courses:["ML Algorithms","Deep Learning","NLP","Model Deployment"],district:"Sri Sathya Sai",register:"https://www.mygreatlearning.com/signup"},
{name:"Great Learning — DS (Sri Sathya Sai)",skill:"Data Science",rating:4.5,reviews_count:1600,address:"Sri Sathya Sai, Andhra Pradesh",phone:"",email:"",website:"https://www.mygreatlearning.com",description:"PG programs in Data Science from top universities with placement support.",hours:["Online — 24/7"],location:{lat:14.2,lng:77.61},courses:["Data Science PG","Analytics","Python","Machine Learning"],district:"Sri Sathya Sai",register:"https://www.mygreatlearning.com/signup"},
{name:"OpenClassrooms — Programming",skill:"Programming",rating:4.3,reviews_count:600,address:"Sri Sathya Sai, Andhra Pradesh",phone:"",email:"",website:"https://openclassrooms.com",description:"European online education platform with diploma programs in web development and data.",hours:["Online — 24/7"],location:{lat:14.2,lng:77.61},courses:["Web Dev","Python","JavaScript","Data Analysis"],district:"Sri Sathya Sai",register:"https://openclassrooms.com/en/registration"},
{name:"Great Learning — AI (Sri Sathya Sai)",skill:"Artificial Intelligence",rating:4.5,reviews_count:1600,address:"Sri Sathya Sai, Andhra Pradesh",phone:"",email:"",website:"https://www.mygreatlearning.com/ai",description:"AI and ML programs with industry projects and expert mentoring.",hours:["Online — 24/7"],location:{lat:14.2,lng:77.61},courses:["AI Engineering","Deep Learning","NLP","Computer Vision"],district:"Sri Sathya Sai",register:"https://www.mygreatlearning.com/signup"},

// 24. Kurnool
{name:"Rayalaseema University — ML",skill:"Machine Learning",rating:4.1,reviews_count:200,address:"Kurnool, Andhra Pradesh",phone:"",email:"",website:"https://rayalaseemauniversity.ac.in",description:"ML and data analytics programs at Rayalaseema University with research emphasis.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:15.8281,lng:78.0373},courses:["ML Fundamentals","Data Mining","Pattern Recognition","Research"],district:"Kurnool",register:"https://rayalaseemauniversity.ac.in/admissions"},
{name:"Rayalaseema University — DS",skill:"Data Science",rating:4.1,reviews_count:200,address:"Kurnool, Andhra Pradesh",phone:"",email:"",website:"https://rayalaseemauniversity.ac.in",description:"Data Science and statistics programs at Rayalaseema University.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:15.8281,lng:78.0373},courses:["Statistics","Data Analytics","R","Python"],district:"Kurnool",register:"https://rayalaseemauniversity.ac.in/admissions"},
{name:"Treehouse — Programming",skill:"Programming",rating:4.4,reviews_count:1200,address:"Kurnool, Andhra Pradesh",phone:"",email:"",website:"https://teamtreehouse.com",description:"Learn coding, web design, and development with video-based interactive courses.",hours:["Online — 24/7"],location:{lat:15.8281,lng:78.0373},courses:["Python","JavaScript","Swift","PHP"],district:"Kurnool",register:"https://teamtreehouse.com/signup"},
{name:"Rayalaseema University — AI",skill:"Artificial Intelligence",rating:4.1,reviews_count:200,address:"Kurnool, Andhra Pradesh",phone:"",email:"",website:"https://rayalaseemauniversity.ac.in",description:"AI research and education programs at Rayalaseema University.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:15.8281,lng:78.0373},courses:["AI Basics","Neural Networks","Expert Systems","Robotics"],district:"Kurnool",register:"https://rayalaseemauniversity.ac.in/admissions"},

// 25. Nandyal
{name:"Simplilearn — ML (Nandyal)",skill:"Machine Learning",rating:4.4,reviews_count:1400,address:"Nandyal, Andhra Pradesh",phone:"",email:"",website:"https://www.simplilearn.com",description:"Professional ML certification courses with project-based learning.",hours:["Online — 24/7"],location:{lat:15.4786,lng:78.4836},courses:["ML Certification","Supervised Learning","Model Tuning","Deployment"],district:"Nandyal",register:"https://www.simplilearn.com/login"},
{name:"Simplilearn — DS (Nandyal)",skill:"Data Science",rating:4.4,reviews_count:1400,address:"Nandyal, Andhra Pradesh",phone:"",email:"",website:"https://www.simplilearn.com",description:"Data Science bootcamp with industry mentorship and placement support.",hours:["Online — 24/7"],location:{lat:15.4786,lng:78.4836},courses:["Data Science PG","Python","R","Power BI"],district:"Nandyal",register:"https://www.simplilearn.com/login"},
{name:"Springboard — Programming",skill:"Programming",rating:4.4,reviews_count:800,address:"Nandyal, Andhra Pradesh",phone:"",email:"",website:"https://www.springboard.com",description:"Mentor-guided bootcamps with job guarantee in software engineering and data.",hours:["Online — 24/7"],location:{lat:15.4786,lng:78.4836},courses:["Software Engineering","Data Engineering","ML Engineering","UX"],district:"Nandyal",register:"https://www.springboard.com/signup"},
{name:"Udacity — AI (Nandyal)",skill:"Artificial Intelligence",rating:4.5,reviews_count:1200,address:"Nandyal, Andhra Pradesh",phone:"",email:"",website:"https://www.udacity.com/school-of-ai",description:"Nanodegree programs in AI, deep learning, and computer vision from Udacity.",hours:["Online — 24/7"],location:{lat:15.4786,lng:78.4836},courses:["AI Programming","Deep Learning","Computer Vision","NLP"],district:"Nandyal",register:"https://www.udacity.com/account/auth#!/signup"},

// 26. Parvathipuram Manyam
{name:"Coursera — ML (Parvathipuram Manyam)",skill:"Machine Learning",rating:4.7,reviews_count:2200,address:"Parvathipuram Manyam, AP",phone:"",email:"",website:"https://www.coursera.org",description:"Access world-class ML courses from Stanford and Google on Coursera.",hours:["Online — 24/7"],location:{lat:18.7668,lng:83.4339},courses:["ML Specialization","Deep Learning","TensorFlow","AI"],district:"Parvathipuram Manyam",register:"https://www.coursera.org/join"},
{name:"Coursera — DS (Parvathipuram Manyam)",skill:"Data Science",rating:4.7,reviews_count:2200,address:"Parvathipuram Manyam, AP",phone:"",email:"",website:"https://www.coursera.org",description:"Professional Data Science certificates from IBM and Google.",hours:["Online — 24/7"],location:{lat:18.7668,lng:83.4339},courses:["IBM DS","Google DA","Python","SQL"],district:"Parvathipuram Manyam",register:"https://www.coursera.org/join"},
{name:"Khan Academy — Programming",skill:"Programming",rating:4.8,reviews_count:10000,address:"Parvathipuram Manyam, AP",phone:"",email:"",website:"https://www.khanacademy.org",description:"Free world-class education. Learn computing, programming, and algorithms at your own pace.",hours:["Online — 24/7"],location:{lat:18.7668,lng:83.4339},courses:["JS","HTML/CSS","SQL","Algorithms"],district:"Parvathipuram Manyam",register:"https://www.khanacademy.org/signup"},
{name:"SWAYAM — AI Academy",skill:"Artificial Intelligence",rating:4.3,reviews_count:3000,address:"Parvathipuram Manyam, AP",phone:"",email:"",website:"https://swayam.gov.in",description:"Government of India's free online education platform with NPTEL AI and ML courses from IITs.",hours:["Online — 24/7"],location:{lat:18.7668,lng:83.4339},courses:["NPTEL ML","AI Basics","Deep Learning","Data Science"],district:"Parvathipuram Manyam",register:"https://swayam.gov.in/signup"}
];
module.exports = { TECH_ACADEMIES };