/*  ═══════════════════════════════════════════════════════
    COMPETITIONS DATA — ML, AI, DS, Academic, Quiz, Debate
    ═══════════════════════════════════════════════════════ */
const EXTRA_COMPETITIONS = [
    // ── ML / AI / DATA SCIENCE COMPETITIONS ──
    { id: "ml001", name: "Kaggle Competitions", category: "Machine Learning", skill: "Machine Learning", date: "2026-06-30", time: "Ongoing", deadline: "2026-12-31", location: "Online", venue: "Kaggle Platform", organizer: "Kaggle (Google)", description: "The world's largest data science competition platform with continuous ML, Data Science, AI, and Deep Learning challenges. New competitions every month with prediction challenges, NLP, and computer vision tasks.", prize: "Varies (up to $100K)", eligibility: "Open to students + professionals", team_size: "Individual or Team", phone: "", email: "", website: " https://www.kaggle.com", registration_link: "https://www.kaggle.com/competitions", coords: { lat: 17.3850, lng: 78.4867 } },
    { id: "ml002", name: "Analytics Vidhya DataHack — The Smart Recruits", category: "Data Science", skill: "Data Science", date: "2026-06-15", time: "Ongoing", deadline: "2026-06-30", location: "Online (India-focused)", venue: "Analytics Vidhya Platform", organizer: "Analytics Vidhya", description: "Popular Indian data science competition platform. Active recurring challenges with ML, analytics, and business problem solving. Cash prizes and hiring opportunities from top companies.", prize: "Cash prizes + hiring", eligibility: "Open to all", team_size: "Individual or Team", phone: "", email: "", website: " https://www.kaggle.com⁠", registration_link: "https://datahack.analyticsvidhya.com", coords: { lat: 28.6139, lng: 77.2090 } },
    { id: "ml003", name: "ML Contests (Global ML Challenges)", category: "Machine Learning", skill: "Machine Learning", date: "2026-06-30", time: "Ongoing", deadline: "2026-12-31", location: "Online", venue: "Multiple Platforms", organizer: "ML Contests Aggregator", description: "Aggregates 20+ active competitions at once including AI research problems, predictive modeling, and healthcare/environment ML challenges.", prize: "Varies by competition", eligibility: "Open to all", team_size: "Varies", phone: "", email: "", website: "https://mlcontests.com", registration_link: "https://mlcontests.com", coords: { lat: 17.3850, lng: 78.4867 } },
    { id: "ml004", name: "Amazon Nova AI Challenge 2026", category: "Artificial Intelligence", skill: "Artificial Intelligence", date: "2026-08-15", time: "Ongoing", deadline: "2026-09-30", location: "Online (India eligible)", venue: "Amazon Platform", organizer: "Amazon Web Services", description: "Focuses on advanced AI systems, LLM applications, AI agents, and safe AI systems. Global recognition and prizes for innovative solutions.", prize: "Global recognition + prizes", eligibility: "Open to all (India eligible)", team_size: "1–5 members", phone: "", email: "", website: "https://www.kaggle.com⁠", registration_link: "https://nova.amazon.com/challenge", coords: { lat: 17.3850, lng: 78.4867 } },
    { id: "ml005", name: "ITU AI/ML in 5G Challenge", category: "Artificial Intelligence", skill: "Artificial Intelligence", date: "2026-07-01", time: "Spring–Summer cycle", deadline: "2026-08-31", location: "Online", venue: "ITU Platform", organizer: "International Telecommunication Union", description: "Active global challenge focusing on 5G/6G + ML and Telecom AI. Work with industry experts on cutting-edge telecommunications AI problems.", prize: "Industry recognition", eligibility: "Students & professionals worldwide", team_size: "1–4 members", phone: "", email: "", website: "https://www.kaggle.com⁠", registration_link: "https://aiforgood.itu.int/about-ai-ml-in-5g-challenge/", coords: { lat: 46.2044, lng: 6.1432 } },
    { id: "ml006", name: "AgentathonX / GenAI Hackathons", category: "Artificial Intelligence", skill: "Artificial Intelligence", date: "2026-05-15", time: "April–May", deadline: "2026-05-30", location: "Online (India)", venue: "Online Platform", organizer: "Various India-based organizers", description: "Multiple overlapping hackathons focused on Generative AI, ML agents, and programming. Includes AgentathonX, GenAI Hackathon, and DigitalOcean AI Hackathon.", prize: "Varies by event", eligibility: "Developers & students", team_size: "1–4 members", phone: "", email: "", website: "https://www.kaggle.com⁠", registration_link: "https://unstop.com", coords: { lat: 28.6139, lng: 77.2090 } },
    { id: "ml007", name: "GDG AI/ML Project Competition", category: "Machine Learning", skill: "Machine Learning", date: "2026-06-20", time: "April–June events", deadline: "2026-06-15", location: "Hybrid / Offline (India)", venue: "GDG Campus chapters", organizer: "Google Developer Groups India", description: "Build real-world AI/ML projects judged by industry experts. Conducted frequently across college campuses in India. Great for portfolio building.", prize: "Certificates + merchandize", eligibility: "Students", team_size: "2–4 members", phone: "", email: "", website: "https://www.kaggle.com⁠", registration_link: "https://gdg.community.dev", coords: { lat: 17.3850, lng: 78.4867 } },
    { id: "ml008", name: "FutureX 2026 — National AI Challenge", category: "Artificial Intelligence", skill: "Artificial Intelligence", date: "2026-07-10", time: "2026 cycle active", deadline: "2026-07-01", location: "India-wide", venue: "Multiple Indian cities", organizer: "FutureX India", description: "National AI challenge focusing on AI + IoT + coding innovation. Real-world AI problem solving with mentorship and prizes.", prize: "₹1,00,000+", eligibility: "Students (school & college)", team_size: "1–3 members", phone: "", email: "", website: "https://www.kaggle.com⁠", registration_link: "https://futurex.in/register", coords: { lat: 12.9716, lng: 77.5946 } },
    { id: "ml009", name: "ICAIML Conference + Competition Track", category: "Machine Learning", skill: "Machine Learning", date: "2026-05-20", time: "May 2026", deadline: "2026-04-30", location: "India", venue: "Conference venue TBA", organizer: "ICAIML Committee", description: "Academic + competition hybrid event with AI/ML paper competition and data science research tracks.", prize: "Publication + recognition", eligibility: "Researchers & students", team_size: "Individual or Team", phone: "", email: "", website: "https://icaiml.org", registration_link: "https://www.kaggle.com⁠", coords: { lat: 13.0827, lng: 80.2707 } },
    { id: "ml010", name: "AI/Data Science Conference Series (Chennai)", category: "Data Science", skill: "Data Science", date: "2026-06-25", time: "April–June 2026", deadline: "2026-06-15", location: "Chennai, India", venue: "Various Chennai venues", organizer: "Industry consortiums", description: "Series including AI Healthcare Informatics (April), Deep Reinforcement Learning (May), and AI-driven Data Science (June). Paper presentations and competitions.", prize: "Publication + certificates", eligibility: "Researchers & professionals", team_size: "Individual", phone: "", email: "", website: "https://www.kaggle.com⁠", registration_link: "https://waset.org", coords: { lat: 13.0827, lng: 80.2707 } },

    // ── ACADEMIC / QUIZ COMPETITIONS ──
    { id: "quiz001", name: "MyGov India — Viksit Bharat Quiz 2026", category: "Quiz", skill: "Quiz", date: "2026-06-30", time: "Ongoing", deadline: "2026-06-30", location: "Online (India)", venue: "MyGov India Platform", organizer: "Government of India", description: "National online quiz on India's development, achievements, and vision. Free participation with instant certificate. Quiz starts immediately after registration.", prize: "Free certificate", eligibility: "All Indian citizens", team_size: "Individual", phone: "", email: "", website: "https://quiz.mygov.in", registration_link: "https://quiz.mygov.in/quiz/the-viksit-bharat-quiz-2026-english/", coords: { lat: 28.6139, lng: 77.2090 } },
    { id: "quiz002", name: "Scholastic World — National Online Quiz Series", category: "Quiz", skill: "Quiz", date: "2026-05-30", time: "Ongoing with April deadlines", deadline: "2026-05-30", location: "Online (India)", venue: "Scholastic World Platform", organizer: "Scholastic World", description: "Multiple active quizzes on GK, India achievements, and current affairs. Multiple quizzes run throughout the year for school and college students.", prize: "Certificates + prizes", eligibility: "School & college students", team_size: "Individual", phone: "", email: "", website: "https://www.sporcle.com", registration_link: "https://scholasticworld.in/", coords: { lat: 28.6139, lng: 77.2090 } },
    { id: "quiz003", name: "Dublieu — Upcoming Quiz Competitions Hub", category: "Quiz", skill: "Quiz", date: "2026-06-30", time: "Continuous", deadline: "2026-12-31", location: "Online", venue: "Dublieu Platform", organizer: "Dublieu", description: "Platform aggregating national and international quiz competitions. Lists multiple active quiz contests throughout the year.", prize: "Varies by competition", eligibility: "Students", team_size: "Individual or Team", phone: "", email: "", website: "https://kahoot.com⁠", registration_link: "https://www.dublieu.com/find-upcoming-quiz-competitions-for-students-in-2026", coords: { lat: 28.6139, lng: 77.2090 } },

    // ── DEBATE COMPETITIONS ──
    { id: "debate001", name: "Smt. Sushma Swaraj Memorial National Parliamentary Debate", category: "Debate", skill: "Debate", date: "2026-04-15", time: "Early April 2026", deadline: "2026-04-10", location: "Delhi, India", venue: "University of Delhi Law Centre II", organizer: "University of Delhi", description: "One of India's major parliamentary debate competitions. Cash prizes and recognition from DU Law Centre.", prize: "Cash prizes", eligibility: "College students", team_size: "2 members", phone: "", email: "", website: "https://www.behes.org/", registration_link: "https://www.lawctopus.com/smt-sushma-swaraj-memorial-national-parliamentary-debate-by-university-of-delhi/", coords: { lat: 28.7041, lng: 77.1025 } },
    { id: "debate002", name: "Verbatim 3.0 National Debate Competition 2026", category: "Debate", skill: "Debate", date: "2026-06-15", time: "Registration till August", deadline: "2026-08-15", location: "Greater Noida, India", venue: "Lloyd Law College", organizer: "Lloyd Law College", description: "National debate competition for UG and PG students. Conventional debate format with extended registration window.", prize: "Cash prizes + certificates", eligibility: "UG & PG students", team_size: "Individual", phone: "", email: "", website: "https://www.speakforindia.com/", registration_link: "https://www.lawctopus.com/verbatim-3-0-national-debate-competition-2026-at-lloyd-law-college/", coords: { lat: 28.4744, lng: 77.5040 } },
    { id: "debate003", name: "Speech & Debate India × Harvard Championship Series", category: "Debate", skill: "Debate", date: "2026-05-15", time: "March–April rolling entry", deadline: "2026-05-30", location: "Online (India)", venue: "Online Platform", organizer: "Speech & Debate India × Harvard Debate Council", description: "Weekly debates and competitions with global exposure. Certification and connections with Harvard debate community.", prize: "Certification + global exposure", eligibility: "School students", team_size: "Individual", phone: "", email: "", website: "https://www.indiandebatingleague.com/", registration_link: "https://live.speechdebateindia.com/", coords: { lat: 28.6139, lng: 77.2090 } },
    { id: "debate004", name: "Speak for India — National Debate Competition", category: "Debate", skill: "Debate", date: "2026-07-01", time: "Multi-phase (district → national)", deadline: "2026-06-30", location: "Multiple Indian states", venue: "Multiple venues across India", organizer: "Speak for India Foundation", description: "Large-scale Indian debate competition with district to national rounds. Available in English, Hindi, and regional languages.", prize: "National recognition + prizes", eligibility: "College students", team_size: "Individual", phone: "", email: "", website: "https://www.lawctopus.com/category/opportunities-events/debates/", registration_link: "https://www.speakforindia.com/maharashtra", coords: { lat: 19.0760, lng: 72.8777 } },

]; module.exports = { EXTRA_COMPETITIONS };
