const LEGACY_ACADEMIES = [
        // ── Legacy Ongole Academies (original) ──
        {
            name: "Prakasam Tech Institute",
            skill: "Programming",
            rating: 4.4,
            reviews_count: 86,
            address: "Bhagya Nagar, Ongole, Andhra Pradesh 523002",
            phone: "+91 90123 45678",
            email: "contact@prakasamtech.in",
            website: "https://prakasamtech.in",
            description: "Industry-focused programming courses with hands-on projects. Specializing in C++, Python, and web technologies. Internship partnerships with leading IT companies.",
            hours: ["Mon–Sat: 8:00 AM – 7:00 PM", "Sun: 10:00 AM – 2:00 PM"],
            location: { lat: 15.5030, lng: 80.0520 },
            courses: ["C++ Programming", "Web Technologies", "Database Management"]
        },
        {
            name: "DataMinds Analytics Lab",
            skill: "Data Science",
            rating: 4.6,
            reviews_count: 72,
            address: "Court Centre, Ongole, Andhra Pradesh 523001",
            phone: "+91 87654 32190",
            email: "learn@datamindslab.com",
            website: "https://datamindslab.com",
            description: "Specialized in Data Science and Analytics. Courses include R programming, Tableau, Power BI, and advanced statistical modeling. Weekend batches available for working professionals.",
            hours: ["Mon–Fri: 9:30 AM – 7:30 PM", "Sat–Sun: 10:00 AM – 4:00 PM"],
            location: { lat: 15.5045, lng: 80.0465 },
            courses: ["Data Analysis with Python", "R Programming", "Tableau", "Power BI"]
        },
        {
            name: "AI Vision Academy",
            skill: "Artificial Intelligence",
            rating: 4.8,
            reviews_count: 54,
            address: "Kurnool Road, Ongole, Andhra Pradesh 523002",
            phone: "+91 91234 56780",
            email: "admissions@aivisionacademy.com",
            website: "https://aivisionacademy.com",
            description: "Cutting-edge AI and Deep Learning training center. Hands-on experience with TensorFlow, PyTorch, and computer vision. Research-oriented curriculum designed by IIT alumni.",
            hours: ["Mon–Fri: 10:00 AM – 8:00 PM", "Sat: 10:00 AM – 3:00 PM", "Sun: Closed"],
            location: { lat: 15.5080, lng: 80.0530 },
            courses: ["Deep Learning", "Natural Language Processing", "Computer Vision", "AI Ethics"]
        },
        {
            name: "NeuroNet ML Hub",
            skill: "Machine Learning",
            rating: 4.5,
            reviews_count: 63,
            address: "Gandhi Nagar, Ongole, Andhra Pradesh 523001",
            phone: "+91 93456 78901",
            email: "hello@neuronetml.com",
            website: "https://neuronetml.com",
            description: "Focused on Machine Learning and predictive analytics. Learn supervised, unsupervised, and reinforcement learning with real-world datasets. Kaggle competition preparation included.",
            hours: ["Mon–Sat: 9:00 AM – 7:00 PM", "Sun: Closed"],
            location: { lat: 15.5065, lng: 80.0480 },
            courses: ["Machine Learning Fundamentals", "Feature Engineering", "Model Deployment", "Kaggle Prep"]
        },

        // ── Creative Skills ──
        {
            name: "Nataraja Dance Academy",
            skill: "Dance",
            rating: 4.8,
            reviews_count: 210,
            address: "Santhapet, Ongole, Andhra Pradesh 523001",
            phone: "+91 97890 12345",
            email: "nataraja.dance@gmail.com",
            website: "https://natarajadance.in",
            description: "Established in 2005, Nataraja is Ongole's premier dance academy teaching Bharatanatyam, Kuchipudi, and contemporary dance. Trained over 2000+ students. Annual recitals at Prakasam Auditorium.",
            hours: ["Mon–Sat: 6:00 AM – 9:00 PM", "Sun: 7:00 AM – 12:00 PM"],
            location: { lat: 15.5035, lng: 80.0445 },
            courses: ["Bharatanatyam", "Kuchipudi", "Contemporary Dance", "Western Dance"]
        },
        {
            name: "Rhythm Steps Dance Studio",
            skill: "Dance",
            rating: 4.5,
            reviews_count: 145,
            address: "Mangamuru Road, Ongole, Andhra Pradesh 523002",
            phone: "+91 96543 21098",
            email: "rhythmsteps.ongole@gmail.com",
            website: "",
            description: "Modern dance studio offering hip-hop, freestyle, Bollywood, and Zumba. Perfect for all age groups. Choreography for weddings and events also available.",
            hours: ["Mon–Sat: 5:30 AM – 8:30 PM", "Sun: 6:00 AM – 11:00 AM"],
            location: { lat: 15.5090, lng: 80.0510 },
            courses: ["Hip-Hop", "Bollywood Dance", "Freestyle", "Zumba"]
        },
        {
            name: "Harmony Music Institute",
            skill: "Music",
            rating: 4.6,
            reviews_count: 178,
            address: "Subash Road, Ongole, Andhra Pradesh 523001",
            phone: "+91 98012 34567",
            email: "harmony.music.ong@gmail.com",
            website: "https://harmonymusicongole.com",
            description: "Learn Carnatic music, Hindustani music, keyboard, guitar, drums, and violin. Faculty trained at Kalakshetra and Sri Venkateswara University. Group and individual sessions available.",
            hours: ["Mon–Sat: 7:00 AM – 9:00 PM", "Sun: 8:00 AM – 1:00 PM"],
            location: { lat: 15.5025, lng: 80.0490 },
            courses: ["Carnatic Vocal", "Guitar", "Keyboard", "Drums", "Violin"]
        },
        {
            name: "Saraswati Music School",
            skill: "Music",
            rating: 4.3,
            reviews_count: 95,
            address: "Rajiv Nagar, Ongole, Andhra Pradesh 523002",
            phone: "+91 94567 89012",
            email: "saraswatimusic@gmail.com",
            website: "",
            description: "Traditional music school specializing in Carnatic vocal and Veena. Over 30 years of cultural heritage. Students regularly perform at temple festivals and cultural events.",
            hours: ["Mon–Sat: 6:30 AM – 8:00 PM", "Sun: Closed"],
            location: { lat: 15.5010, lng: 80.0470 },
            courses: ["Carnatic Vocal", "Veena", "Flute", "Mridangam"]
        },
        {
            name: "SwaraSudhha Singing Academy",
            skill: "Singing",
            rating: 4.7,
            reviews_count: 112,
            address: "Ashok Nagar, Ongole, Andhra Pradesh 523001",
            phone: "+91 95678 90123",
            email: "swarasudhha@gmail.com",
            website: "https://swarasudhha.in",
            description: "Voice training academy for classical and playback singing. Certified vocal coaches. Students have participated in TV reality shows like Sa Re Ga Ma Pa and Indian Idol.",
            hours: ["Mon–Fri: 8:00 AM – 7:00 PM", "Sat: 8:00 AM – 5:00 PM", "Sun: Closed"],
            location: { lat: 15.5072, lng: 80.0455 },
            courses: ["Classical Vocal", "Playback Singing", "Voice Modulation", "Stage Performance"]
        },
        {
            name: "Kala Niketan Art Studio",
            skill: "Painting",
            rating: 4.4,
            reviews_count: 88,
            address: "Balaji Nagar, Ongole, Andhra Pradesh 523002",
            phone: "+91 92345 67890",
            email: "kalaniketan.art@gmail.com",
            website: "https://kalaniketan.art",
            description: "Fine arts studio offering watercolor, oil painting, sketching, and digital art. Art exhibitions held quarterly. Students' works featured in state-level competitions.",
            hours: ["Mon–Sat: 10:00 AM – 7:00 PM", "Sun: 10:00 AM – 1:00 PM"],
            location: { lat: 15.5048, lng: 80.0435 },
            courses: ["Watercolor Painting", "Oil Painting", "Pencil Sketching", "Digital Art"]
        },
        {
            name: "Canvas Dreams Art Academy",
            skill: "Painting",
            rating: 4.2,
            reviews_count: 65,
            address: "Chennakesava Peta, Ongole, Andhra Pradesh 523001",
            phone: "+91 93210 98765",
            email: "canvasdreams.og@gmail.com",
            website: "",
            description: "Art classes for beginners and advanced learners. Specializing in acrylic, pastel, and mixed media. Kids' art camps during summer and winter holidays.",
            hours: ["Tue–Sun: 9:00 AM – 6:00 PM", "Mon: Closed"],
            location: { lat: 15.5015, lng: 80.0510 },
            courses: ["Acrylic Painting", "Pastel Art", "Mixed Media", "Kids Art Camp"]
        },

        // ── Fitness & Wellness ──
        {
            name: "Shanti Yoga Ashram",
            skill: "Yoga",
            rating: 4.9,
            reviews_count: 235,
            address: "Venkateswara Nagar, Ongole, Andhra Pradesh 523001",
            phone: "+91 96789 01234",
            email: "shantiyoga.ongole@gmail.com",
            website: "https://shantiyogaashram.org",
            description: "Authentic yoga training center with certified yoga gurus. Hatha Yoga, Ashtanga Yoga, Pranayama, and therapeutic yoga. Early morning and evening batches. Yoga teacher training (200-hour certified).",
            hours: ["Mon–Sun: 5:00 AM – 9:00 PM"],
            location: { lat: 15.5060, lng: 80.0440 },
            courses: ["Hatha Yoga", "Ashtanga Yoga", "Pranayama", "Yoga Teacher Training"]
        },
        {
            name: "Prakruti Yoga Center",
            skill: "Yoga",
            rating: 4.5,
            reviews_count: 120,
            address: "Lawyer Peta, Ongole, Andhra Pradesh 523002",
            phone: "+91 91098 76543",
            email: "prakrutiyoga@gmail.com",
            website: "",
            description: "Community yoga center offering affordable classes. Power yoga, prenatal yoga, and senior citizen programs. Free sessions on International Yoga Day.",
            hours: ["Mon–Sat: 5:30 AM – 8:00 PM", "Sun: 6:00 AM – 10:00 AM"],
            location: { lat: 15.5042, lng: 80.0525 },
            courses: ["Power Yoga", "Prenatal Yoga", "Senior Yoga", "Kids Yoga"]
        },
        {
            name: "Inner Peace Meditation Centre",
            skill: "Meditation",
            rating: 4.7,
            reviews_count: 98,
            address: "Bharathi Nagar, Ongole, Andhra Pradesh 523001",
            phone: "+91 97654 32109",
            email: "innerpeace.ongole@gmail.com",
            website: "https://innerpeacemeditation.in",
            description: "Dedicated meditation center offering Vipassana, mindfulness, and transcendental meditation. Weekend silent retreats available. Guided sessions for stress management and mental wellness.",
            hours: ["Mon–Sun: 5:00 AM – 8:00 PM"],
            location: { lat: 15.5055, lng: 80.0460 },
            courses: ["Vipassana Meditation", "Mindfulness", "Transcendental Meditation", "Stress Relief"]
        },
        {
            name: "Iron Forge Fitness Studio",
            skill: "Fitness Training",
            rating: 4.6,
            reviews_count: 156,
            address: "Kurnool Road, Ongole, Andhra Pradesh 523002",
            phone: "+91 98901 23456",
            email: "ironforge.fitness@gmail.com",
            website: "https://ironforgefitness.com",
            description: "State-of-the-art gym with certified personal trainers. CrossFit, HIIT, strength training, and body transformation programs. Diet and nutrition counseling included with premium plans.",
            hours: ["Mon–Sat: 5:00 AM – 10:00 PM", "Sun: 6:00 AM – 12:00 PM"],
            location: { lat: 15.5078, lng: 80.0535 },
            courses: ["CrossFit", "HIIT Training", "Strength Training", "Weight Loss Program"]
        },
        {
            name: "FitZone Gym & Wellness",
            skill: "Fitness Training",
            rating: 4.3,
            reviews_count: 110,
            address: "Trunk Road, Ongole, Andhra Pradesh 523001",
            phone: "+91 94321 09876",
            email: "fitzone.ongole@gmail.com",
            website: "",
            description: "Modern fitness center with cardio, weight training, and group fitness classes. Zumba, aerobics, and kickboxing. Separate timings for ladies.",
            hours: ["Mon–Sat: 5:00 AM – 10:00 PM", "Sun: 6:00 AM – 11:00 AM"],
            location: { lat: 15.5038, lng: 80.0505 },
            courses: ["Cardio Training", "Aerobics", "Kickboxing", "Ladies Fitness"]
        },

        // ── Sports ──
        {
            name: "Ongole Cricket Academy",
            skill: "Cricket",
            rating: 4.7,
            reviews_count: 290,
            address: "Stadium Road, Ongole, Andhra Pradesh 523001",
            phone: "+91 99876 54321",
            email: "ongolecricket@gmail.com",
            website: "https://ongolecricketacademy.com",
            description: "BCCI-affiliated cricket academy with professional coaching. Net practice, bowling machines, and video analysis. Produced several Ranji Trophy and IPL players. U-14, U-16, and senior batches.",
            hours: ["Mon–Sat: 5:30 AM – 7:00 PM", "Sun: 6:00 AM – 12:00 PM"],
            location: { lat: 15.5050, lng: 80.0475 },
            courses: ["Batting Coaching", "Bowling & Fielding", "Wicket-keeping", "Match Strategy"]
        },
        {
            name: "AP Star Cricket Club",
            skill: "Cricket",
            rating: 4.4,
            reviews_count: 175,
            address: "Railway Station Road, Ongole, Andhra Pradesh 523002",
            phone: "+91 90876 54312",
            email: "apstarcricket@gmail.com",
            website: "",
            description: "Community cricket coaching for all ages. Turf pitch practice available. Regular inter-academy tournaments. Affordable monthly fee structure.",
            hours: ["Mon–Sun: 5:00 AM – 6:00 PM"],
            location: { lat: 15.5020, lng: 80.0540 },
            courses: ["Junior Cricket", "Senior Cricket", "T20 Skills", "Fitness for Cricket"]
        },
        {
            name: "Prakasam Football Academy",
            skill: "Football",
            rating: 4.5,
            reviews_count: 142,
            address: "Bypass Road, Ongole, Andhra Pradesh 523002",
            phone: "+91 91234 56789",
            email: "prakasamfootball@gmail.com",
            website: "https://prakasamfa.com",
            description: "AIFF-recognized football academy with FIFA-trained coaches. Training for all positions. Annual talent scouting events. Players selected for state and national camps.",
            hours: ["Mon–Sat: 5:00 AM – 7:00 PM", "Sun: 5:00 AM – 10:00 AM"],
            location: { lat: 15.5095, lng: 80.0490 },
            courses: ["Football Basics", "Advanced Skills", "Goalkeeper Training", "Tactical Play"]
        },
        {
            name: "Aqua Splash Swimming Academy",
            skill: "Swimming",
            rating: 4.6,
            reviews_count: 168,
            address: "Chimakurthy Road, Ongole, Andhra Pradesh 523001",
            phone: "+91 92109 87654",
            email: "aquasplash.ongole@gmail.com",
            website: "https://aquasplashswim.com",
            description: "Olympic-size pool with temperature control. Learn freestyle, backstroke, butterfly, and breaststroke. Competitive swimming training and water safety programs. Certified lifeguard instructors.",
            hours: ["Mon–Sat: 5:30 AM – 8:00 PM", "Sun: 6:00 AM – 12:00 PM"],
            location: { lat: 15.5040, lng: 80.0420 },
            courses: ["Beginner Swimming", "Competitive Swimming", "Water Safety", "Dive Training"]
        },
        {
            name: "Dragon Warrior Martial Arts",
            skill: "Martial Arts",
            rating: 4.8,
            reviews_count: 130,
            address: "Old Club Road, Ongole, Andhra Pradesh 523001",
            phone: "+91 93456 78012",
            email: "dragonwarrior.ma@gmail.com",
            website: "https://dragonwarriormartialarts.in",
            description: "Training in Karate, Taekwondo, Kung Fu, and Judo. Black-belt instructors with international competition experience. Self-defense programs for women and children.",
            hours: ["Mon–Sat: 6:00 AM – 9:00 PM", "Sun: 7:00 AM – 11:00 AM"],
            location: { lat: 15.5068, lng: 80.0450 },
            courses: ["Karate", "Taekwondo", "Kung Fu", "Self-Defense"]
        },
        {
            name: "Shaolin Combat Academy",
            skill: "Martial Arts",
            rating: 4.3,
            reviews_count: 78,
            address: "Addanki Road, Ongole, Andhra Pradesh 523002",
            phone: "+91 90567 89012",
            email: "shaolincombat.og@gmail.com",
            website: "",
            description: "Mixed martial arts and self-defense training. Muay Thai, Brazilian Jiu-Jitsu, and boxing. Open for kids (6+), teens, and adults. Ring sparring sessions every Saturday.",
            hours: ["Mon–Sat: 6:00 AM – 8:30 PM", "Sun: Closed"],
            location: { lat: 15.5085, lng: 80.0460 },
            courses: ["Mixed Martial Arts", "Muay Thai", "Brazilian Jiu-Jitsu", "Boxing"]
        }
];
module.exports = { LEGACY_ACADEMIES };