/*  ═══════════════════════════════════════════════════════
    CREATIVE & CULTURAL ACADEMIES
    Dance | Music | Singing | Drama | Photography | Painting
    Districts: Vizag, Vijayawada, Guntur, Nellore, Tirupati,
    Kurnool, Anantapur, Kadapa, Rajahmundry, Kakinada, Eluru,
    Srikakulam, Vizianagaram, Ongole, Chittoor
    ═══════════════════════════════════════════════════════ */
const CREATIVE_ACADEMIES = [

// ══════════ VISAKHAPATNAM ══════════
{name:"Pace Creators Dance Academy",skill:"Dance",rating:4.9,reviews_count:400,address:"Ram Nagar, Visakhapatnam, AP",phone:"+91 81433 31691",email:"",website:"https://www.pacecreators.com",description:"Top-rated dance academy in Vizag specializing in hip-hop, freestyle, and choreography. Professional training for all ages.",hours:["Mon–Sat: 6 AM – 9 PM"],location:{lat:17.7230,lng:83.3198},courses:["Hip-Hop","Freestyle","Choreography","Stage Performance"],district:"Visakhapatnam"},
{name:"Broadway Dance Academy",skill:"Dance",rating:4.9,reviews_count:200,address:"MVP Colony, Visakhapatnam, AP",phone:"+91 99669 95311",email:"",website:"https://broadwayacademy.co/",description:"Western and Bollywood dance training for kids and adults. Professional choreography services.",hours:["Mon–Sat: 7 AM – 9 PM"],location:{lat:17.7350,lng:83.3150},courses:["Western Dance","Bollywood","Kids Dance","Adults Training"],district:"Visakhapatnam"},
{name:"TACET Music Academy",skill:"Music",rating:5.0,reviews_count:150,address:"Asilmetta, Visakhapatnam, AP",phone:"+91 70759 65881",email:"",website:"https://www.tacetcentral.com/",description:"Premium music school offering singing, instrument training, and music theory courses.",hours:["Mon–Sat: 9 AM – 8 PM"],location:{lat:17.7200,lng:83.3100},courses:["Singing","Guitar","Keyboard","Music Theory"],district:"Visakhapatnam"},
{name:"MAA Music Academy",skill:"Music",rating:4.7,reviews_count:120,address:"Madhavadhara, Visakhapatnam, AP",phone:"+91 63012 45917",email:"",website:"",description:"Vocal, classical, and instrumental music training in Vizag with experienced faculty.",hours:["Mon–Sat: 7 AM – 8 PM"],location:{lat:17.7400,lng:83.3200},courses:["Carnatic Vocal","Instruments","Classical Music","Light Music"],district:"Visakhapatnam"},
{name:"Satyanand Acting Institute",skill:"Drama",rating:4.5,reviews_count:100,address:"Jagadamba Junction, Visakhapatnam, AP",phone:"+91 92466 23378",email:"",website:"https://www.satyanandactinginstitute.in/",description:"Famous acting school with industry exposure. Training in method acting, dialogue delivery, and screen acting.",hours:["Mon–Sat: 10 AM – 7 PM"],location:{lat:17.7150,lng:83.3050},courses:["Method Acting","Screen Acting","Dialogue Delivery","Direction"],district:"Visakhapatnam"},
{name:"Ganapathi's School Of Photography",skill:"Photography",rating:4.7,reviews_count:80,address:"Pendurthi, Visakhapatnam, AP",phone:"+91 70132 23033",email:"",website:"http://www.ganapathirao.com/",description:"Professional photography courses covering DSLR, editing, and professional photography techniques.",hours:["Mon–Sat: 10 AM – 6 PM"],location:{lat:17.7500,lng:83.2800},courses:["DSLR Photography","Photo Editing","Professional Photography","Portfolio Building"],district:"Visakhapatnam"},
{name:"Art by Usha Drawing & Painting Academy",skill:"Painting",rating:4.8,reviews_count:90,address:"Akkayyapalem, Visakhapatnam, AP",phone:"+91 98488 52039",email:"",website:"http://www.sisyp.com",description:"Drawing and painting classes including sketching, fine arts, and various painting techniques.",hours:["Mon–Sat: 10 AM – 7 PM"],location:{lat:17.7300,lng:83.3100},courses:["Sketching","Painting","Fine Arts","Watercolors"],district:"Visakhapatnam"},

// ══════════ VIJAYAWADA ══════════
{name:"Happy Dance Institute",skill:"Dance",rating:4.9,reviews_count:180,address:"Patamata, Vijayawada, AP",phone:"+91 98856 43643",email:"",website:"https://bdir.in",description:"Popular dance institute in Vijayawada offering Bollywood, Hip-hop, Zumba, and classical dance training.",hours:["Mon–Sat: 6 AM – 9 PM"],location:{lat:16.5062,lng:80.6480},courses:["Bollywood","Hip-hop","Zumba","Classical"],district:"Vijayawada"},
{name:"Freedom Dance and Aerobics School",skill:"Dance",rating:4.8,reviews_count:150,address:"Vijayawada, AP",phone:"+91 98498 28710",email:"",website:"https://instagram.com/freedomdancez",description:"Private and group dance classes with aerobics. Modern dance styles and fitness dance.",hours:["Mon–Sat: 6 AM – 9 PM"],location:{lat:16.5100,lng:80.6400},courses:["Freestyle","Aerobics","Contemporary","Fitness Dance"],district:"Vijayawada"},
{name:"Lawrence Dance Institute",skill:"Dance",rating:4.8,reviews_count:120,address:"Siddhartha Nagar, Vijayawada, AP",phone:"+91 90003 45599",email:"",website:"",description:"Western dance and choreography training for competitions and events.",hours:["Mon–Sat: 5 PM – 9 PM"],location:{lat:16.5000,lng:80.6500},courses:["Western Dance","Choreography","Stage Performance"],district:"Vijayawada"},
{name:"Viswanadh Academy",skill:"Music",rating:4.8,reviews_count:130,address:"Payakapuram, Vijayawada, AP",phone:"+91 79811 20300",email:"",website:"",description:"Classical music and dance training academy with experienced tutors.",hours:["Mon–Sat: 7 AM – 8 PM"],location:{lat:16.5050,lng:80.6350},courses:["Classical Music","Dance","Vocal Training"],district:"Vijayawada"},
{name:"Amaravathi Film Maker Studios",skill:"Drama",rating:5.0,reviews_count:60,address:"Labbipet, Vijayawada, AP",phone:"",email:"",website:"https://sulekha.com",description:"Film production and acting school offering courses in acting, direction, and filmmaking.",hours:["Mon–Sat: 10 AM – 7 PM"],location:{lat:16.5150,lng:80.6200},courses:["Acting","Direction","Filmmaking","Screenwriting"],district:"Vijayawada"},
{name:"Maya Academy (MAAC Vijayawada)",skill:"Photography",rating:4.5,reviews_count:90,address:"Benz Circle, Vijayawada, AP",phone:"+91 9966456377",email:"",website:"https://www.maacvijayawada.com",description:"Photography, filmmaking, VFX, and animation courses at MAAC Vijayawada.",hours:["Mon–Sat: 9 AM – 7 PM"],location:{lat:16.5080,lng:80.6300},courses:["Photography","Filmmaking","VFX","Animation"],district:"Vijayawada"},
{name:"Siva Arts Academy",skill:"Painting",rating:5.0,reviews_count:70,address:"Vijayawada, AP",phone:"",email:"",website:"https://superprof.co.in",description:"Drawing, acrylic, and oil painting courses for beginners and advanced learners.",hours:["Mon–Sat: 10 AM – 6 PM"],location:{lat:16.5062,lng:80.6480},courses:["Drawing","Acrylic Painting","Oil Painting","Sketching"],district:"Vijayawada"},

// ══════════ GUNTUR ══════════
{name:"Karim's Heart Beat Dance Studio",skill:"Dance",rating:5.0,reviews_count:100,address:"Gujjanagundla, Guntur, AP",phone:"+91 93915 69229",email:"",website:"",description:"Western, freestyle, and kids dance classes with energetic choreography sessions.",hours:["Mon–Sat: 6 AM – 9 PM"],location:{lat:16.3067,lng:80.4365},courses:["Western","Freestyle","Kids Dance","Choreography"],district:"Guntur"},
{name:"Sri Manjunadha Kuchipudi Dance Academy",skill:"Dance",rating:5.0,reviews_count:80,address:"Old Guntur, AP",phone:"+91 90141 44177",email:"",website:"",description:"Specialized classical Kuchipudi dance academy with traditional gurukul-style training.",hours:["Mon–Sat: 6 AM – 8 PM"],location:{lat:16.3000,lng:80.4300},courses:["Kuchipudi","Classical Dance"],district:"Guntur"},
{name:"Art of Natraj's",skill:"Dance",rating:4.9,reviews_count:90,address:"Chandramouli Nagar, Guntur, AP",phone:"+91 83099 03498",email:"",website:"",description:"Kuchipudi dance and yoga training with experienced instructors.",hours:["Mon–Sat: 6 AM – 8 PM"],location:{lat:16.3100,lng:80.4400},courses:["Kuchipudi","Yoga","Classical Dance"],district:"Guntur"},
{name:"Royal Music Academy",skill:"Music",rating:4.8,reviews_count:110,address:"Brindavan Gardens, Guntur, AP",phone:"+91 77991 66696",email:"",website:"http://www.royalmusicacademy.in/",description:"Vocal, instruments, and classical music training with certified instructors.",hours:["Mon–Sat: 8 AM – 8 PM"],location:{lat:16.3050,lng:80.4500},courses:["Vocal","Instruments","Classical Music","Music Theory"],district:"Guntur"},
{name:"Amrutha Music Academy",skill:"Singing",rating:4.9,reviews_count:85,address:"Pattabhipuram, Guntur, AP",phone:"+91 97053 25356",email:"",website:"",description:"Carnatic vocal and instrumental music training for all age groups.",hours:["Mon–Sat: 7 AM – 8 PM"],location:{lat:16.3020,lng:80.4380},courses:["Carnatic Vocal","Instruments","Light Music"],district:"Guntur"},
{name:"NRM Cultural Academy",skill:"Drama",rating:4.5,reviews_count:60,address:"Guntur, AP",phone:"",email:"",website:"https://nrmculturalacademy.com/",description:"Dance, drama, music, art under one platform. Cultural training and stage performance.",hours:["Mon–Sat: 9 AM – 7 PM"],location:{lat:16.3067,lng:80.4365},courses:["Drama","Dance","Music","Art"],district:"Guntur"},
{name:"ML Photography",skill:"Photography",rating:4.9,reviews_count:75,address:"NGO Colony, Guntur, AP",phone:"+91 79819 06969",email:"",website:"http://www.mlphotography.in/",description:"Professional photography training and shoots. DSLR courses and wedding photography.",hours:["Mon–Sat: 10 AM – 7 PM"],location:{lat:16.3100,lng:80.4500},courses:["DSLR Photography","Wedding Photography","Editing"],district:"Guntur"},
{name:"Rishita Setty Photography Studio",skill:"Photography",rating:4.8,reviews_count:60,address:"Ashok Nagar, Guntur, AP",phone:"+91 77990 00575",email:"",website:"http://www.rishitasetty.com/",description:"Photography training and professional portrait/fashion photography.",hours:["Mon–Sat: 10 AM – 6 PM"],location:{lat:16.3080,lng:80.4420},courses:["Portrait Photography","Fashion Photography","Photo Editing"],district:"Guntur"},
{name:"Vellaturi Art Academy",skill:"Painting",rating:5.0,reviews_count:95,address:"Chandramouli Nagar, Guntur, AP",phone:"+91 99661 01083",email:"",website:"https://vellaturiartacademy.in/",description:"Drawing, painting, and fine arts training for all levels. Regular exhibitions.",hours:["Mon–Sat: 10 AM – 7 PM"],location:{lat:16.3100,lng:80.4400},courses:["Drawing","Painting","Fine Arts","Sketching"],district:"Guntur"},

// ══════════ NELLORE ══════════
{name:"Vijay Musical Dance Academy",skill:"Dance",rating:4.7,reviews_count:100,address:"BV Nagar, Nellore, AP",phone:"+91 99488 35735",email:"",website:"http://www.vijaymusicaldanceacademy.in",description:"Dance, music, and aerobics classes for all age groups in Nellore.",hours:["Mon–Sat: 6 AM – 9 PM"],location:{lat:14.4426,lng:79.9865},courses:["Dance","Music","Aerobics"],district:"Nellore"},
{name:"Sri Nataraja Kalakshetra",skill:"Dance",rating:5.0,reviews_count:60,address:"Stonehouse Pet, Nellore, AP",phone:"",email:"",website:"https://yappe.in",description:"Classical Kuchipudi dance training with traditional methods.",hours:["Mon–Sat: 6 AM – 8 PM"],location:{lat:14.4400,lng:79.9900},courses:["Kuchipudi","Classical Dance"],district:"Nellore"},
{name:"Government School of Music and Dance",skill:"Music",rating:4.9,reviews_count:130,address:"Somasekara Puram, Nellore, AP",phone:"+91 861 232 8285",email:"",website:"https://spsnellore.ap.gov.in",description:"Government music school offering vocal, veena, violin, and Bharatanatyam training.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:14.4450,lng:79.9880},courses:["Vocal","Veena","Violin","Bharatanatyam"],district:"Nellore"},
{name:"Nakshathra School Cultural Activities",skill:"Drama",rating:4.0,reviews_count:40,address:"Nellore, AP",phone:"+91 8019818888",email:"",website:"https://www.nakshathraschool.com",description:"Drama, arts, and cultural training center for students.",hours:["Mon–Sat: 9 AM – 5 PM"],location:{lat:14.4426,lng:79.9865},courses:["Drama","Arts","Cultural Training"],district:"Nellore"},

// ══════════ TIRUPATI ══════════
{name:"ABCD Dance Academy",skill:"Dance",rating:4.8,reviews_count:90,address:"Tirupati, AP",phone:"+91 89777 96663",email:"",website:"https://wanderlog.com",description:"Western dance, freestyle, and fitness dance training for all ages.",hours:["Mon–Sat: 6 AM – 9 PM"],location:{lat:13.6288,lng:79.4192},courses:["Western Dance","Freestyle","Fitness Dance"],district:"Tirupati"},
{name:"Sri Nrithyanjali Academy Of Music & Dance",skill:"Dance",rating:4.8,reviews_count:110,address:"Tirupati, AP",phone:"+91 98494 45981",email:"",website:"https://sri-nrithyanjali-academy-of-music-dance.business.site",description:"Bharatanatyam, Kuchipudi, and music training with cultural performances.",hours:["Mon–Sat: 6 AM – 8 PM"],location:{lat:13.6300,lng:79.4200},courses:["Bharatanatyam","Kuchipudi","Music"],district:"Tirupati"},
{name:"Ardhanareeswara Kuchipudi Dance Academy",skill:"Dance",rating:4.9,reviews_count:80,address:"Tirupati, AP",phone:"+91 91107 34022",email:"",website:"https://wanderlog.com",description:"Classical Kuchipudi dance training with expert guidance.",hours:["Mon–Sat: 6 AM – 8 PM"],location:{lat:13.6250,lng:79.4150},courses:["Kuchipudi","Classical Dance"],district:"Tirupati"},
{name:"Varna Music Academy",skill:"Music",rating:4.4,reviews_count:70,address:"Tirupati, AP",phone:"+91 99801 44267",email:"",website:"https://justdial.com",description:"Carnatic vocal and instrument training with experienced faculty.",hours:["Mon–Sat: 8 AM – 8 PM"],location:{lat:13.6288,lng:79.4192},courses:["Carnatic Vocal","Instruments","Music Theory"],district:"Tirupati"},
{name:"Bhavamai Kala Niketan",skill:"Painting",rating:4.6,reviews_count:55,address:"Tirupati, AP",phone:"+91 99497 10376",email:"",website:"https://tirupationline.in",description:"Drawing, painting, and cultural arts training for all age groups.",hours:["Mon–Sat: 10 AM – 6 PM"],location:{lat:13.6288,lng:79.4192},courses:["Drawing","Painting","Cultural Arts"],district:"Tirupati"},

// ══════════ KURNOOL ══════════
{name:"SS Dance Academy",skill:"Dance",rating:4.9,reviews_count:120,address:"Madhav Nagar, C Camp, Kurnool, AP",phone:"+91 97033 72112",email:"",website:"",description:"Western and freestyle dance training with stage performance preparation.",hours:["Mon–Sat: 6 AM – 9 PM"],location:{lat:15.8281,lng:78.0373},courses:["Western Dance","Freestyle","Stage Performance"],district:"Kurnool"},
{name:"AS Dance & Fitness Academy",skill:"Dance",rating:4.9,reviews_count:80,address:"SVR Colony, Kurnool, AP",phone:"+91 82978 25197",email:"",website:"",description:"Dance and fitness academy combining dance training with aerobic fitness.",hours:["Mon–Sat: 6 AM – 9 PM"],location:{lat:15.8300,lng:78.0400},courses:["Dance","Fitness","Aerobics","Zumba"],district:"Kurnool"},
{name:"T.G.V. Kalakshetram Dance Academy",skill:"Dance",rating:4.5,reviews_count:70,address:"C-Camp Circle, Kurnool, AP",phone:"+91 99636 28418",email:"",website:"",description:"Cultural arts and classical dance training with stage performances.",hours:["Mon–Sat: 6 AM – 8 PM"],location:{lat:15.8260,lng:78.0350},courses:["Classical Dance","Cultural Arts","Stage Performance"],district:"Kurnool"},
{name:"Cornerstone Music Institute",skill:"Music",rating:4.9,reviews_count:100,address:"B Camp, Kurnool, AP",phone:"+91 90525 07754",email:"",website:"https://cornerstonemusicstores.in",description:"Keyboard, guitar, and vocal training with professional music equipment store.",hours:["Mon–Sat: 9 AM – 8 PM"],location:{lat:15.8250,lng:78.0350},courses:["Keyboard","Guitar","Vocal","Drums"],district:"Kurnool"},
{name:"Rhythmz Institute of Music",skill:"Music",rating:4.9,reviews_count:75,address:"Joharapuram Road, Kurnool, AP",phone:"+91 72077 71312",email:"",website:"",description:"Music and singing training institute with professional-grade facilities.",hours:["Mon–Sat: 9 AM – 8 PM"],location:{lat:15.8330,lng:78.0420},courses:["Music","Singing","Instruments"],district:"Kurnool"},
{name:"Zoom Studios",skill:"Photography",rating:4.7,reviews_count:85,address:"Bangar Pet, Kurnool, AP",phone:"+91 92999 98080",email:"",website:"",description:"Photography services and training for professionals.",hours:["Mon–Sat: 10 AM – 7 PM"],location:{lat:15.8281,lng:78.0373},courses:["Photography","Editing","Videography"],district:"Kurnool"},
{name:"Sree Vaishnavi Arts and Tutorials",skill:"Painting",rating:5.0,reviews_count:65,address:"SVR Colony, Kurnool, AP",phone:"+91 98480 14384",email:"",website:"",description:"Drawing and painting lessons for all skill levels.",hours:["Mon–Sat: 10 AM – 6 PM"],location:{lat:15.8300,lng:78.0400},courses:["Drawing","Painting","Sketching"],district:"Kurnool"},
{name:"The Anjali Way",skill:"Painting",rating:5.0,reviews_count:50,address:"A Camp, Kurnool, AP",phone:"",email:"",website:"https://www.theanjaliway.com",description:"Art school offering fine arts and creative arts training.",hours:["Mon–Sat: 10 AM – 6 PM"],location:{lat:15.8260,lng:78.0380},courses:["Fine Arts","Creative Arts","Painting"],district:"Kurnool"},

// ══════════ ANANTAPUR ══════════
{name:"Siva Dance Academy",skill:"Dance",rating:4.8,reviews_count:90,address:"Ram Nagar, Anantapur, AP",phone:"+91 94903 45678",email:"",website:"https://justdial.com",description:"Western and classical dance training with experienced instructors.",hours:["Mon–Sat: 6 AM – 9 PM"],location:{lat:14.6819,lng:77.6006},courses:["Western Dance","Classical Dance","Freestyle"],district:"Anantapuramu"},
{name:"Nataraja Dance Academy Anantapur",skill:"Dance",rating:4.9,reviews_count:80,address:"Kamalanagar, Anantapur, AP",phone:"+91 98480 22334",email:"",website:"https://urbanpro.com",description:"Bharatanatyam and Kuchipudi dance training with traditional methods.",hours:["Mon–Sat: 6 AM – 8 PM"],location:{lat:14.6850,lng:77.6050},courses:["Bharatanatyam","Kuchipudi","Classical Dance"],district:"Anantapuramu"},
{name:"Swaralaya Music Institute",skill:"Music",rating:4.9,reviews_count:75,address:"Ashok Nagar, Anantapur, AP",phone:"+91 88866 11223",email:"",website:"https://swaralayaacademy.in",description:"Vocal and instrumental music training with modern methods.",hours:["Mon–Sat: 8 AM – 8 PM"],location:{lat:14.6800,lng:77.5950},courses:["Vocal","Instruments","Music Theory"],district:"Anantapuramu"},
{name:"Sangeetha Kala Academy",skill:"Singing",rating:4.8,reviews_count:65,address:"Old Town, Anantapur, AP",phone:"+91 97012 34567",email:"",website:"https://urbanpro.com",description:"Carnatic vocal training and classical music education.",hours:["Mon–Sat: 7 AM – 8 PM"],location:{lat:14.6819,lng:77.6006},courses:["Carnatic Vocal","Classical Music","Light Music"],district:"Anantapuramu"},
{name:"Nataraja Cultural Academy",skill:"Drama",rating:4.6,reviews_count:50,address:"Clock Tower Area, Anantapur, AP",phone:"+91 98481 23456",email:"",website:"https://sulekha.com",description:"Acting, stage performance, and cultural training institute.",hours:["Mon–Sat: 10 AM – 7 PM"],location:{lat:14.6830,lng:77.6020},courses:["Acting","Stage Performance","Drama"],district:"Anantapuramu"},
{name:"Pixel Photography Academy",skill:"Photography",rating:4.8,reviews_count:60,address:"Subash Road, Anantapur, AP",phone:"+91 97000 12345",email:"",website:"https://urbanpro.com",description:"DSLR photography and editing courses for aspiring photographers.",hours:["Mon–Sat: 10 AM – 7 PM"],location:{lat:14.6819,lng:77.6006},courses:["DSLR Photography","Photo Editing","Portrait Photography"],district:"Anantapuramu"},
{name:"Chitra Kala Art School",skill:"Painting",rating:4.8,reviews_count:55,address:"Ashok Nagar, Anantapur, AP",phone:"+91 97012 88990",email:"",website:"https://justdial.com",description:"Drawing, painting, and fine arts training for all levels.",hours:["Mon–Sat: 10 AM – 6 PM"],location:{lat:14.6800,lng:77.5950},courses:["Drawing","Painting","Fine Arts"],district:"Anantapuramu"},

// ══════════ YSR KADAPA ══════════
{name:"Mudra Dance School",skill:"Dance",rating:4.9,reviews_count:150,address:"Housing Board Colony, Kadapa, AP",phone:"",email:"",website:"https://mudradanceschool.business.site",description:"Top-rated dance school in Kadapa for western and stage performances.",hours:["Mon–Sat: 6 AM – 9 PM"],location:{lat:14.4673,lng:78.8242},courses:["Western Dance","Stage Performance","Choreography"],district:"YSR Kadapa"},
{name:"Kadapa Dance School",skill:"Dance",rating:3.8,reviews_count:50,address:"APHB Colony, Kadapa, AP",phone:"+91 86390 91839",email:"",website:"https://yappe.in",description:"Basic and freestyle dance training for all age groups.",hours:["Mon–Sat: 6 AM – 8 PM"],location:{lat:14.4700,lng:78.8280},courses:["Freestyle","Basic Dance","Kids Dance"],district:"YSR Kadapa"},
{name:"Sri Sai Music Academy Kadapa",skill:"Music",rating:4.5,reviews_count:60,address:"NGO Colony, Kadapa, AP",phone:"+91 94912 34567",email:"",website:"https://justdial.com",description:"Keyboard, guitar, and music training for beginners and intermediate learners.",hours:["Mon–Sat: 9 AM – 8 PM"],location:{lat:14.4673,lng:78.8242},courses:["Keyboard","Guitar","Music Theory"],district:"YSR Kadapa"},
{name:"Natya Kala Bharathi",skill:"Drama",rating:4.4,reviews_count:45,address:"Kadapa, AP",phone:"+91 93767 17777",email:"",website:"https://dreamweddinghub.com",description:"Acting, stage performance, and cultural arts training.",hours:["Mon–Sat: 10 AM – 7 PM"],location:{lat:14.4673,lng:78.8242},courses:["Acting","Stage Performance","Cultural Arts"],district:"YSR Kadapa"},
{name:"Sivaa Studio's & Color Lab",skill:"Photography",rating:4.6,reviews_count:200,address:"Maria Puram, Kadapa, AP",phone:"",email:"",website:"https://yappe.in",description:"Photography services, training, and digital editing courses.",hours:["Mon–Sat: 10 AM – 7 PM"],location:{lat:14.4650,lng:78.8200},courses:["Photography","Photo Editing","Studio Photography"],district:"YSR Kadapa"},

// ══════════ RAJAHMUNDRY ══════════
{name:"Nataraja Dance Academy Rajahmundry",skill:"Dance",rating:4.8,reviews_count:110,address:"Danavaipeta, Rajahmundry, AP",phone:"+91 98665 43210",email:"",website:"https://justdial.com",description:"Classical Kuchipudi and Bharatanatyam dance training with experienced faculty.",hours:["Mon–Sat: 6 AM – 8 PM"],location:{lat:17.0005,lng:81.8040},courses:["Kuchipudi","Bharatanatyam","Classical Dance"],district:"East Godavari"},
{name:"Rhythm Dance Academy Rajahmundry",skill:"Dance",rating:4.9,reviews_count:90,address:"Morampudi, Rajahmundry, AP",phone:"+91 93939 11223",email:"",website:"https://urbanpro.com",description:"Freestyle and cinematic dance training for competitions and events.",hours:["Mon–Sat: 5 PM – 9 PM"],location:{lat:17.0050,lng:81.8100},courses:["Freestyle","Cinematic Dance","Stage Performance"],district:"East Godavari"},
{name:"Swaralaya Music Academy Rajahmundry",skill:"Music",rating:4.9,reviews_count:80,address:"Jampeta, Rajahmundry, AP",phone:"+91 90300 45678",email:"",website:"https://swaralayaacademy.in",description:"Guitar, keyboard, and vocal music training with modern methods.",hours:["Mon–Sat: 9 AM – 8 PM"],location:{lat:17.0020,lng:81.8050},courses:["Guitar","Keyboard","Vocal","Music Theory"],district:"East Godavari"},
{name:"Sangeetha Kala Academy Rajahmundry",skill:"Singing",rating:4.8,reviews_count:70,address:"Innespeta, Rajahmundry, AP",phone:"+91 97012 34567",email:"",website:"https://urbanpro.com",description:"Classical singing and Carnatic vocal training for all ages.",hours:["Mon–Sat: 7 AM – 8 PM"],location:{lat:17.0005,lng:81.8040},courses:["Carnatic Vocal","Classical Singing","Light Music"],district:"East Godavari"},
{name:"Kalabharathi Cultural Academy Rajahmundry",skill:"Drama",rating:4.6,reviews_count:55,address:"Kotipalli Bus Stand Area, Rajahmundry, AP",phone:"+91 98481 23456",email:"",website:"https://sulekha.com",description:"Acting and theatre training with cultural program organization.",hours:["Mon–Sat: 10 AM – 7 PM"],location:{lat:17.0030,lng:81.8080},courses:["Acting","Theatre","Cultural Programs"],district:"East Godavari"},
{name:"Chitra Kala Art School Rajahmundry",skill:"Painting",rating:4.8,reviews_count:65,address:"Innespeta, Rajahmundry, AP",phone:"+91 97012 88990",email:"",website:"https://justdial.com",description:"Drawing and painting courses for beginners and advanced students.",hours:["Mon–Sat: 10 AM – 6 PM"],location:{lat:17.0005,lng:81.8040},courses:["Drawing","Painting","Sketching","Fine Arts"],district:"East Godavari"},

// ══════════ KAKINADA ══════════
{name:"Nataraja Dance Academy Kakinada",skill:"Dance",rating:4.8,reviews_count:95,address:"Bhanugudi Junction, Kakinada, AP",phone:"+91 98665 43210",email:"",website:"https://justdial.com",description:"Bharatanatyam and Kuchipudi classical dance training.",hours:["Mon–Sat: 6 AM – 8 PM"],location:{lat:16.9891,lng:82.2475},courses:["Bharatanatyam","Kuchipudi","Classical Dance"],district:"Kakinada"},
{name:"Rhythm Dance Academy Kakinada",skill:"Dance",rating:4.9,reviews_count:75,address:"Jagannaickpur, Kakinada, AP",phone:"+91 93939 11223",email:"",website:"https://urbanpro.com",description:"Western and cinematic dance training with performance preparation.",hours:["Mon–Sat: 5 PM – 9 PM"],location:{lat:16.9920,lng:82.2500},courses:["Western Dance","Cinematic Dance","Choreography"],district:"Kakinada"},
{name:"Swaralaya Music Academy Kakinada",skill:"Music",rating:4.9,reviews_count:70,address:"Suryaraopeta, Kakinada, AP",phone:"+91 90300 45678",email:"",website:"https://swaralayaacademy.in",description:"Guitar, piano, and vocal music training with modern facilities.",hours:["Mon–Sat: 9 AM – 8 PM"],location:{lat:16.9880,lng:82.2450},courses:["Guitar","Piano","Vocal","Music Theory"],district:"Kakinada"},
{name:"Sangeetha Kala Academy Kakinada",skill:"Singing",rating:4.8,reviews_count:65,address:"Ramaraopeta, Kakinada, AP",phone:"+91 97012 34567",email:"",website:"https://urbanpro.com",description:"Carnatic music and vocal training with experienced faculty.",hours:["Mon–Sat: 7 AM – 8 PM"],location:{lat:16.9891,lng:82.2475},courses:["Carnatic Vocal","Classical Singing"],district:"Kakinada"},
{name:"Kalabharathi Cultural Academy Kakinada",skill:"Drama",rating:4.6,reviews_count:50,address:"Jagannaickpur, Kakinada, AP",phone:"+91 98481 23456",email:"",website:"https://sulekha.com",description:"Acting and theatre training center with drama productions.",hours:["Mon–Sat: 10 AM – 7 PM"],location:{lat:16.9920,lng:82.2500},courses:["Acting","Theatre","Drama"],district:"Kakinada"},
{name:"Chitra Kala Art School Kakinada",skill:"Painting",rating:4.8,reviews_count:55,address:"Ramaraopeta, Kakinada, AP",phone:"+91 97012 88990",email:"",website:"https://justdial.com",description:"Drawing and painting training for all levels.",hours:["Mon–Sat: 10 AM – 6 PM"],location:{lat:16.9891,lng:82.2475},courses:["Drawing","Painting","Sketching","Fine Arts"],district:"Kakinada"},

// ══════════ ELURU ══════════
{name:"Spark Dance Academy",skill:"Dance",rating:4.7,reviews_count:70,address:"Ameenapet, Eluru, AP",phone:"+91 73969 88336",email:"",website:"https://justdial.com",description:"Western and freestyle dance training for all ages.",hours:["Mon–Sat: 6 AM – 9 PM"],location:{lat:16.7107,lng:81.0952},courses:["Western Dance","Freestyle"],district:"Eluru"},
{name:"Kalabhoomi Dance Studio",skill:"Dance",rating:4.7,reviews_count:60,address:"Santhi Nagar, Eluru, AP",phone:"+91 79016 31999",email:"",website:"https://justdial.com",description:"Classical and modern dance training studio.",hours:["Mon–Sat: 6 AM – 9 PM"],location:{lat:16.7150,lng:81.0900},courses:["Classical Dance","Modern Dance"],district:"Eluru"},
{name:"Kaladeepika Dance Academy",skill:"Dance",rating:4.5,reviews_count:55,address:"Powerpet, Eluru, AP",phone:"+91 94412 66236",email:"",website:"https://justdial.com",description:"Kuchipudi and Bharatanatyam classical dance training.",hours:["Mon–Sat: 6 AM – 8 PM"],location:{lat:16.7107,lng:81.0952},courses:["Kuchipudi","Bharatanatyam"],district:"Eluru"},
{name:"Raja Music Academy",skill:"Music",rating:4.9,reviews_count:80,address:"Chanikyapuri Colony, Eluru, AP",phone:"+91 85230 17776",email:"",website:"https://justdial.com",description:"Keyboard, guitar, and music training with experienced educators.",hours:["Mon–Sat: 9 AM – 8 PM"],location:{lat:16.7107,lng:81.0952},courses:["Keyboard","Guitar","Music Theory"],district:"Eluru"},
{name:"Sruti College of Music",skill:"Singing",rating:4.9,reviews_count:70,address:"Kandrikagudem, Eluru, AP",phone:"+91 97038 30935",email:"",website:"https://justdial.com",description:"Classical singing and Carnatic vocal training college.",hours:["Mon–Sat: 8 AM – 7 PM"],location:{lat:16.7080,lng:81.1000},courses:["Classical Singing","Carnatic Vocal"],district:"Eluru"},
{name:"Hema Studio 9",skill:"Photography",rating:4.8,reviews_count:90,address:"Ramachandra Rao Pet, Eluru, AP",phone:"+91 98481 68363",email:"",website:"https://hemastudio9.com/",description:"Photography training and professional studio services.",hours:["Mon–Sat: 10 AM – 7 PM"],location:{lat:16.7107,lng:81.0952},courses:["Photography","Photo Editing","Videography"],district:"Eluru"},
{name:"Keshav Photography",skill:"Photography",rating:4.8,reviews_count:75,address:"Narasimharao Pet, Eluru, AP",phone:"+91 88866 44868",email:"",website:"https://keshavphotography.com/",description:"Wedding and professional photography training.",hours:["Mon–Sat: 10 AM – 7 PM"],location:{lat:16.7120,lng:81.0980},courses:["Wedding Photography","Professional Photography"],district:"Eluru"},
{name:"Prakash Arts",skill:"Painting",rating:5.0,reviews_count:60,address:"Sanivarapupeta, Eluru, AP",phone:"+91 40276 37444",email:"",website:"https://www.prakasharts.com/",description:"Drawing and fine arts training with exhibitions.",hours:["Mon–Sat: 10 AM – 6 PM"],location:{lat:16.7107,lng:81.0952},courses:["Drawing","Fine Arts","Painting"],district:"Eluru"},

// ══════════ SRIKAKULAM ══════════
{name:"Yoga City Charitable Trust Dance",skill:"Dance",rating:4.5,reviews_count:55,address:"Srikakulam, AP",phone:"",email:"",website:"https://www.sulekha.com/yoga-classes-at-home/srikakulam",description:"Dance and yoga combo training with therapeutic approaches.",hours:["Mon–Sat: 6 AM – 8 PM"],location:{lat:18.2949,lng:83.8938},courses:["Dance","Yoga","Fitness Dance"],district:"Srikakulam"},
{name:"Heartfulness Meditation & Yoga Center",skill:"Dance",rating:5.0,reviews_count:45,address:"A.P.H.B Colony, Srikakulam, AP",phone:"+91 94419 67457",email:"",website:"https://heartfulness.org",description:"Meditation and Raja Yoga programs with dance and cultural activities.",hours:["Mon–Sat: 5 AM – 8 PM"],location:{lat:18.2960,lng:83.8950},courses:["Raja Yoga","Meditation","Cultural Dance"],district:"Srikakulam"},
{name:"Prajapita Brahma Kumaris Srikakulam",skill:"Music",rating:4.5,reviews_count:40,address:"C.B. Road, Srikakulam, AP",phone:"",email:"",website:"https://www.brahmakumaris.org",description:"Spiritual yoga and meditation classes with music and cultural activities.",hours:["Mon–Sat: 6 AM – 7 PM"],location:{lat:18.2949,lng:83.8938},courses:["Spiritual Music","Meditation","Yoga"],district:"Srikakulam"},
{name:"Gym Box Fitness Studio (Arts)",skill:"Photography",rating:4.8,reviews_count:50,address:"Ramalaxman Junction, Srikakulam, AP",phone:"",email:"",website:"https://www.britishschooloflanguages.com/yoga-classes/srikakulam",description:"Photography, fitness, and creative arts training center.",hours:["Mon–Sat: 6 AM – 9 PM"],location:{lat:18.2970,lng:83.8960},courses:["Photography","Fitness","Creative Arts"],district:"Srikakulam"},

// ══════════ VIZIANAGARAM ══════════
{name:"Step By Step Dance Fitness",skill:"Dance",rating:4.7,reviews_count:59,address:"Fort Area, Vizianagaram, AP",phone:"+91 70042 05220",email:"",website:"https://instagram.com",description:"Fitness dance and western-style training for all ages.",hours:["Mon–Sat: 6 AM – 9 PM"],location:{lat:18.1067,lng:83.3956},courses:["Fitness Dance","Western Dance","Freestyle"],district:"Vizianagaram"},
{name:"Dharma's Music & Dance Academy",skill:"Dance",rating:4.6,reviews_count:38,address:"Cantonment, Vizianagaram, AP",phone:"",email:"",website:"https://justdial.com",description:"Combined music and dance training academy.",hours:["Mon–Sat: 6 AM – 8 PM"],location:{lat:18.1100,lng:83.4000},courses:["Dance","Music","Classical Dance"],district:"Vizianagaram"},
{name:"STRINGS Music Academy",skill:"Music",rating:4.9,reviews_count:90,address:"Cantonment, Vizianagaram, AP",phone:"",email:"",website:"https://facebook.com",description:"Guitar, keyboard, and music training with experienced instructors.",hours:["Mon–Sat: 9 AM – 8 PM"],location:{lat:18.1100,lng:83.4000},courses:["Guitar","Keyboard","Music Theory"],district:"Vizianagaram"},
{name:"Amrutha Sree Varshini School of M.A.D",skill:"Painting",rating:4.5,reviews_count:45,address:"Thota Palem, Vizianagaram, AP",phone:"",email:"",website:"https://sulekha.com",description:"Music, arts, and dance training with painting classes.",hours:["Mon–Sat: 10 AM – 6 PM"],location:{lat:18.1050,lng:83.3900},courses:["Painting","Drawing","Arts","Dance"],district:"Vizianagaram"},

// ══════════ CHITTOOR ══════════
{name:"Aarya Dance Company",skill:"Dance",rating:4.9,reviews_count:80,address:"KR Palli, Chittoor, AP",phone:"+91 95500 74523",email:"",website:"https://justdial.com",description:"Western and freestyle dance training with choreography services.",hours:["Mon–Sat: 6 AM – 9 PM"],location:{lat:13.2172,lng:79.1003},courses:["Western Dance","Freestyle","Choreography"],district:"Chittoor"},
{name:"R Cube Dance Studio",skill:"Dance",rating:4.9,reviews_count:75,address:"Mittoor, Chittoor, AP",phone:"+91 89784 29125",email:"",website:"https://justdial.com",description:"Cinematic dance and choreography training studio.",hours:["Mon–Sat: 6 AM – 9 PM"],location:{lat:13.2200,lng:79.1050},courses:["Cinematic Dance","Choreography"],district:"Chittoor"},
{name:"El Shaddai Music Institute",skill:"Music",rating:4.9,reviews_count:65,address:"Church Street, Chittoor, AP",phone:"+91 93986 88474",email:"",website:"https://justdial.com",description:"Keyboard, guitar, and vocal music training.",hours:["Mon–Sat: 9 AM – 8 PM"],location:{lat:13.2172,lng:79.1003},courses:["Keyboard","Guitar","Vocal"],district:"Chittoor"},
{name:"Rejo Institute Of Music",skill:"Music",rating:5.0,reviews_count:55,address:"KR Palli, Chittoor, AP",phone:"+91 70134 21139",email:"",website:"https://justdial.com",description:"Vocal and instrumental music training with modern methods.",hours:["Mon–Sat: 9 AM – 8 PM"],location:{lat:13.2150,lng:79.0980},courses:["Vocal","Instruments","Music Theory"],district:"Chittoor"},
{name:"Sai Lokesh Photography",skill:"Photography",rating:4.9,reviews_count:70,address:"Greamspet, Chittoor, AP",phone:"+91 85550 42171",email:"",website:"https://instagram.com",description:"Wedding and photography training with professional services.",hours:["Mon–Sat: 10 AM – 7 PM"],location:{lat:13.2172,lng:79.1003},courses:["Wedding Photography","Training","Editing"],district:"Chittoor"},

// ══════════ ONGOLE ══════════
{name:"Nataraja Dance Academy Ongole",skill:"Dance",rating:4.8,reviews_count:210,address:"Santhapet, Ongole, AP 523001",phone:"+91 97890 12345",email:"nataraja.dance@gmail.com",website:"https://natarajadance.in",description:"Established in 2005, Ongole's premier dance academy teaching Bharatanatyam, Kuchipudi, and contemporary dance.",hours:["Mon–Sat: 6 AM – 9 PM","Sun: 7 AM – 12 PM"],location:{lat:15.5035,lng:80.0445},courses:["Bharatanatyam","Kuchipudi","Contemporary Dance","Western Dance"],district:"Ongole"},
{name:"Rhythm Steps Dance Studio",skill:"Dance",rating:4.5,reviews_count:145,address:"Mangamuru Road, Ongole, AP 523002",phone:"+91 96543 21098",email:"rhythmsteps.ongole@gmail.com",website:"",description:"Modern dance studio offering hip-hop, freestyle, Bollywood, and Zumba for all age groups.",hours:["Mon–Sat: 5:30 AM – 8:30 PM"],location:{lat:15.5090,lng:80.0510},courses:["Hip-Hop","Bollywood Dance","Freestyle","Zumba"],district:"Ongole"},
{name:"Harmony Music Institute",skill:"Music",rating:4.6,reviews_count:178,address:"Subash Road, Ongole, AP 523001",phone:"+91 98012 34567",email:"harmony.music.ong@gmail.com",website:"https://harmonymusicongole.com",description:"Learn Carnatic, Hindustani music, keyboard, guitar, drums, and violin from trained faculty.",hours:["Mon–Sat: 7 AM – 9 PM"],location:{lat:15.5025,lng:80.0490},courses:["Carnatic Vocal","Guitar","Keyboard","Drums","Violin"],district:"Ongole"},
{name:"Saraswati Music School",skill:"Music",rating:4.3,reviews_count:95,address:"Rajiv Nagar, Ongole, AP 523002",phone:"+91 94567 89012",email:"saraswatimusic@gmail.com",website:"",description:"Traditional music school specializing in Carnatic vocal and Veena. Over 30 years of heritage.",hours:["Mon–Sat: 6:30 AM – 8 PM"],location:{lat:15.5010,lng:80.0470},courses:["Carnatic Vocal","Veena","Flute","Mridangam"],district:"Ongole"},
{name:"SwaraSudhha Singing Academy",skill:"Singing",rating:4.7,reviews_count:112,address:"Ashok Nagar, Ongole, AP 523001",phone:"+91 95678 90123",email:"swarasudhha@gmail.com",website:"https://swarasudhha.in",description:"Voice training academy for classical and playback singing. Students participated in TV reality shows.",hours:["Mon–Fri: 8 AM – 7 PM","Sat: 8 AM – 5 PM"],location:{lat:15.5072,lng:80.0455},courses:["Classical Vocal","Playback Singing","Voice Modulation","Stage Performance"],district:"Ongole"},
{name:"Kala Niketan Art Studio",skill:"Painting",rating:4.4,reviews_count:88,address:"Balaji Nagar, Ongole, AP 523002",phone:"+91 92345 67890",email:"kalaniketan.art@gmail.com",website:"https://kalaniketan.art",description:"Fine arts studio offering watercolor, oil painting, sketching, and digital art.",hours:["Mon–Sat: 10 AM – 7 PM"],location:{lat:15.5048,lng:80.0435},courses:["Watercolor","Oil Painting","Sketching","Digital Art"],district:"Ongole"},
{name:"Canvas Dreams Art Academy",skill:"Painting",rating:4.2,reviews_count:65,address:"Chennakesava Peta, Ongole, AP 523001",phone:"+91 93210 98765",email:"canvasdreams.og@gmail.com",website:"",description:"Art classes for beginners and advanced. Specializing in acrylic, pastel, and mixed media.",hours:["Tue–Sun: 9 AM – 6 PM"],location:{lat:15.5015,lng:80.0510},courses:["Acrylic Painting","Pastel Art","Mixed Media","Kids Art Camp"],district:"Ongole"}
];
module.exports = { CREATIVE_ACADEMIES };