/*  ═══════════════════════════════════════════════════════
    SPORTS & FITNESS ACADEMIES — AP Districts
    Sports: Cricket | Football | Swimming | Martial Arts
    Fitness: Yoga | Gym | Fitness Training
    ═══════════════════════════════════════════════════════ */
const SPORTS_FITNESS_ACADEMIES = [

// ══════════ VISAKHAPATNAM — SPORTS ══════════
{name:"Academy for Cricket Excellence (ACE)",skill:"Cricket",rating:4.8,reviews_count:150,address:"Sontyam, Visakhapatnam, AP",phone:"+91 81213 34894",email:"",website:"https://aceforcricket.com",description:"Premier cricket academy in Vizag with professional coaching, net practice, and video analysis.",hours:["Mon–Sat: 5:30 AM – 7 PM"],location:{lat:17.7600,lng:83.3400},courses:["Batting","Bowling","Fielding","Match Strategy"],district:"Visakhapatnam"},
{name:"RR Cricket Academy",skill:"Cricket",rating:4.7,reviews_count:120,address:"Madhurawada, Visakhapatnam, AP",phone:"+91 8328188847",email:"",website:"",description:"Cricket coaching for all ages with turf practice and bowling machines.",hours:["Mon–Sat: 5:30 AM – 6 PM"],location:{lat:17.7800,lng:83.3600},courses:["Junior Cricket","Senior Cricket","T20 Skills"],district:"Visakhapatnam"},
{name:"AG Cricket Academy",skill:"Cricket",rating:4.8,reviews_count:90,address:"Yendada, Visakhapatnam, AP",phone:"",email:"",website:"",description:"Professional cricket coaching with experienced coaches and modern facilities.",hours:["Mon–Sat: 5 AM – 6 PM"],location:{lat:17.7400,lng:83.3000},courses:["Cricket Coaching","Net Practice","Fitness"],district:"Visakhapatnam"},
{name:"Sri Miracle Cricket Academy",skill:"Cricket",rating:5.0,reviews_count:40,address:"Seethamadhara, Visakhapatnam, AP",phone:"",email:"",website:"",description:"High-rated cricket training with personalized coaching.",hours:["Mon–Sat: 5 AM – 6 PM"],location:{lat:17.7350,lng:83.3180},courses:["Batting","Bowling","Match Skills"],district:"Visakhapatnam"},
{name:"BLUESTAR Football Club",skill:"Football",rating:5.0,reviews_count:60,address:"Andhra University Ground, Visakhapatnam, AP",phone:"+91 7702088558",email:"",website:"",description:"Football training club based at AU grounds with professional coaching.",hours:["Mon–Sat: 5 AM – 7 PM"],location:{lat:17.7308,lng:83.3186},courses:["Football Basics","Advanced Skills","Match Play"],district:"Visakhapatnam"},
{name:"Aqua Sports Complex",skill:"Swimming",rating:4.1,reviews_count:180,address:"Pandurangapuram, Visakhapatnam, AP",phone:"+91 8912567413",email:"",website:"https://www.theaquasports.com/",description:"Swimming training with temperature-controlled pool. Certified instructors for all levels.",hours:["Mon–Sat: 5:30 AM – 8 PM"],location:{lat:17.7200,lng:83.3100},courses:["Beginner Swimming","Competitive Swimming","Water Safety"],district:"Visakhapatnam"},
{name:"Indian Modern Martial Arts Academy",skill:"Martial Arts",rating:4.9,reviews_count:130,address:"MVP Colony, Visakhapatnam, AP",phone:"+91 9885498066",email:"",website:"http://indianmodernmartialartsacademyvizag.blogspot.com/",description:"Training in martial arts with international competition experience. Self-defense programs available.",hours:["Mon–Sat: 6 AM – 9 PM"],location:{lat:17.7350,lng:83.3150},courses:["Karate","Taekwondo","Self-Defense","MMA"],district:"Visakhapatnam"},

// ══════════ VISAKHAPATNAM — FITNESS ══════════
{name:"Sree Kiran Yoga Centre",skill:"Yoga",rating:5.0,reviews_count:399,address:"Dwaraka Nagar, Visakhapatnam, AP",phone:"+91 9381787878",email:"",website:"",description:"Highest-rated yoga center in Vizag with therapeutic and traditional yoga programs.",hours:["Mon–Sun: 5 AM – 9 PM"],location:{lat:17.7250,lng:83.3080},courses:["Hatha Yoga","Therapeutic Yoga","Pranayama","Meditation"],district:"Visakhapatnam"},
{name:"Swastika Yoga Studio",skill:"Yoga",rating:5.0,reviews_count:91,address:"Daba Gardens, Visakhapatnam, AP",phone:"+91 8630000952",email:"",website:"",description:"Premium yoga studio with personalized training and wellness programs.",hours:["Mon–Sat: 5 AM – 8 PM"],location:{lat:17.7180,lng:83.3050},courses:["Power Yoga","Ashtanga","Prenatal Yoga","Meditation"],district:"Visakhapatnam"},
{name:"Yoga Science Institute",skill:"Yoga",rating:5.0,reviews_count:101,address:"MVP Colony, Visakhapatnam, AP",phone:"+91 9966010824",email:"",website:"",description:"Scientific approach to yoga with certified instructors and therapy sessions.",hours:["Mon–Sat: 5 AM – 8 PM"],location:{lat:17.7350,lng:83.3150},courses:["Yoga Therapy","Pranayama","Meditation","Flexibility"],district:"Visakhapatnam"},
{name:"Cult Gym Siripuram",skill:"Fitness Training",rating:4.3,reviews_count:126,address:"Siripuram, Visakhapatnam, AP",phone:"+91 7337316830",email:"",website:"",description:"Modern fitness center with group fitness, yoga, and strength training.",hours:["Mon–Sat: 5 AM – 10 PM"],location:{lat:17.7200,lng:83.3200},courses:["CrossFit","HIIT","Yoga","Strength Training"],district:"Visakhapatnam"},
{name:"ABS Fitness Gym",skill:"Fitness Training",rating:4.7,reviews_count:144,address:"Seethammadara, Visakhapatnam, AP",phone:"+91 9505494477",email:"",website:"",description:"Premium gym with cardio, strength training, and personal training programs.",hours:["Mon–Sat: 5 AM – 10 PM"],location:{lat:17.7300,lng:83.3050},courses:["Cardio","Weight Training","Personal Training"],district:"Visakhapatnam"},
{name:"Rams Fitness360",skill:"Fitness Training",rating:4.9,reviews_count:177,address:"Gajuwaka, Visakhapatnam, AP",phone:"+91 7013007841",email:"",website:"",description:"Comprehensive fitness center with personal training and body transformation programs.",hours:["Mon–Sat: 5 AM – 10 PM"],location:{lat:17.7100,lng:83.2100},courses:["Body Transformation","Weight Loss","Strength","Personal Training"],district:"Visakhapatnam"},

// ══════════ VIJAYAWADA — SPORTS ══════════
{name:"Crictrics Cricket Academy",skill:"Cricket",rating:4.9,reviews_count:80,address:"Indranayak Nagar, Vijayawada, AP",phone:"+91 8341830835",email:"",website:"",description:"Professional cricket coaching with modern training methodology.",hours:["Mon–Sat: 5:30 AM – 6 PM"],location:{lat:16.5062,lng:80.6480},courses:["Batting","Bowling","Fielding","Fitness"],district:"Vijayawada"},
{name:"Best Sports Club Cricket Academy",skill:"Cricket",rating:4.3,reviews_count:65,address:"Kanuru, Vijayawada, AP",phone:"+91 9171436999",email:"",website:"",description:"Community cricket academy with affordable coaching for all ages.",hours:["Mon–Sat: 5 AM – 6 PM"],location:{lat:16.5100,lng:80.6600},courses:["Junior Cricket","Senior Cricket","T20"],district:"Vijayawada"},
{name:"Elite Karate Academy",skill:"Martial Arts",rating:5.0,reviews_count:50,address:"Guru Nanak Colony, Vijayawada, AP",phone:"",email:"",website:"",description:"Karate training with black-belt instructors for kids and adults.",hours:["Mon–Sat: 6 AM – 9 PM"],location:{lat:16.5080,lng:80.6350},courses:["Karate","Self-Defense","Competition Training"],district:"Vijayawada"},
{name:"Champions Karate Academy",skill:"Martial Arts",rating:4.9,reviews_count:45,address:"Tarapet, Vijayawada, AP",phone:"",email:"",website:"",description:"Martial arts championship preparation with professional training.",hours:["Mon–Sat: 6 AM – 8 PM"],location:{lat:16.5020,lng:80.6420},courses:["Karate","Taekwondo","Self-Defense"],district:"Vijayawada"},

// ══════════ VIJAYAWADA — FITNESS ══════════
{name:"Divya Shakthi Yoga Studio",skill:"Yoga",rating:4.8,reviews_count:90,address:"Tulasi Nagar, Kanuru, Vijayawada, AP",phone:"+91 89772 77742",email:"",website:"",description:"Yoga, meditation, and holistic wellness programs for all ages.",hours:["Mon–Sat: 5 AM – 8 PM"],location:{lat:16.5100,lng:80.6600},courses:["Hatha Yoga","Meditation","Holistic Wellness"],district:"Vijayawada"},
{name:"Harmony Yoga Center",skill:"Yoga",rating:5.0,reviews_count:65,address:"Mogalrajapuram, Vijayawada, AP",phone:"+91 7036711097",email:"",website:"",description:"Online + offline yoga sessions with flexible timings and personalized training.",hours:["Mon–Sun: 5 AM – 8 PM"],location:{lat:16.5000,lng:80.6300},courses:["Power Yoga","Ashtanga","Pranayama"],district:"Vijayawada"},
{name:"Vedavyas Yoga Studio",skill:"Yoga",rating:4.9,reviews_count:75,address:"Guru Nanak Colony Road, Vijayawada, AP",phone:"+91 9177842098",email:"",website:"",description:"Beginner to advanced yoga programs with certified instructors.",hours:["Mon–Sat: 5 AM – 8 PM"],location:{lat:16.5080,lng:80.6350},courses:["Beginners Yoga","Advanced Yoga","Meditation"],district:"Vijayawada"},
{name:"New Golden Fitness Gym",skill:"Fitness Training",rating:4.9,reviews_count:110,address:"Ayodhya Nagar, Vijayawada, AP",phone:"+91 8142833444",email:"",website:"",description:"Modern gym with strength and cardio training. Personal coaching available.",hours:["Mon–Sat: 5 AM – 10 PM"],location:{lat:16.5150,lng:80.6550},courses:["Strength Training","Cardio","Personal Training"],district:"Vijayawada"},
{name:"Level Up Personal Training Studio",skill:"Fitness Training",rating:5.0,reviews_count:55,address:"Guru Nanak Colony, Vijayawada, AP",phone:"+91 9675474849",email:"",website:"",description:"Specialized personal training and body transformation programs.",hours:["Mon–Sat: 5 AM – 10 PM"],location:{lat:16.5080,lng:80.6350},courses:["Personal Training","Transformation","Weight Loss"],district:"Vijayawada"},

// ══════════ GUNTUR — SPORTS ══════════
{name:"Cricket Academy of Pathans (CAP)",skill:"Cricket",rating:4.5,reviews_count:75,address:"Namburu, NH5 Service Road, Guntur, AP",phone:"+91 9849662231",email:"",website:"",description:"Professional cricket coaching with certified trainers and modern facilities.",hours:["Mon–Sat: 5:30 AM – 6 PM"],location:{lat:16.3067,lng:80.4365},courses:["Batting","Bowling","Fielding","Match Strategy"],district:"Guntur"},
{name:"Power Martial Arts Academy",skill:"Martial Arts",rating:4.9,reviews_count:60,address:"Brodipet, Guntur, AP",phone:"+91 9949525677",email:"",website:"",description:"Kung fu and martial arts training with competitive preparation.",hours:["Mon–Sat: 6 AM – 9 PM"],location:{lat:16.3050,lng:80.4350},courses:["Kung Fu","Karate","Self-Defense"],district:"Guntur"},
{name:"Kasinadh Martial Arts Academy",skill:"Martial Arts",rating:5.0,reviews_count:40,address:"Vidyanagar, Guntur, AP",phone:"",email:"",website:"",description:"Taekwondo training with champion-level instruction for all ages.",hours:["Mon–Sat: 6 AM – 8 PM"],location:{lat:16.3100,lng:80.4450},courses:["Taekwondo","Self-Defense","Competition"],district:"Guntur"},

// ══════════ GUNTUR — FITNESS ══════════
{name:"Varthamaan Yoga",skill:"Yoga",rating:5.0,reviews_count:70,address:"Rajendra Nagar South, Guntur, AP",phone:"+91 9392187954",email:"",website:"",description:"Full-time yoga classes, meditation, and therapy sessions.",hours:["Mon–Sat: 5 AM – 8 PM"],location:{lat:16.3067,lng:80.4365},courses:["Yoga","Meditation","Therapy"],district:"Guntur"},
{name:"Yoga Vidya Pranic Healing Center",skill:"Yoga",rating:5.0,reviews_count:50,address:"Krishna Nagar, Guntur, AP",phone:"",email:"",website:"",description:"Specialized in pranayama and healing yoga. Holistic wellness center.",hours:["Mon–Sat: 5 AM – 7 PM"],location:{lat:16.3020,lng:80.4380},courses:["Pranayama","Healing Yoga","Meditation"],district:"Guntur"},
{name:"Snap Gym Guntur",skill:"Fitness Training",rating:4.5,reviews_count:85,address:"Lakshmipuram Main Road, Guntur, AP",phone:"+91 9863636347",email:"",website:"",description:"International chain gym with modern equipment and group classes.",hours:["Mon–Sat: 5 AM – 10 PM"],location:{lat:16.3067,lng:80.4365},courses:["Cardio","Strength","Group Fitness","Personal Training"],district:"Guntur"},
{name:"RS Gym",skill:"Fitness Training",rating:4.9,reviews_count:95,address:"Pattabhipuram Road, Guntur, AP",phone:"+91 8686337043",email:"",website:"",description:"Highly rated local gym with strength training and bodybuilding.",hours:["Mon–Sat: 5 AM – 10 PM"],location:{lat:16.3020,lng:80.4380},courses:["Strength Training","Bodybuilding","Cardio"],district:"Guntur"},

// ══════════ NELLORE — SPORTS ══════════
{name:"Cricket Institute of Andhra",skill:"Cricket",rating:4.4,reviews_count:60,address:"Central Prison Road, Nellore, AP",phone:"+91 8861498295",email:"",website:"",description:"Cricket training institute with professional coaching for all skill levels.",hours:["Mon–Sat: 5:30 AM – 6 PM"],location:{lat:14.4426,lng:79.9865},courses:["Batting","Bowling","Fielding","Match Strategy"],district:"Nellore"},
{name:"Smashbounce Indoor Sports",skill:"Football",rating:4.4,reviews_count:45,address:"Nellore, AP",phone:"",email:"",website:"",description:"Indoor sports facility with football and multi-sport training.",hours:["Mon–Sat: 6 AM – 10 PM"],location:{lat:14.4450,lng:79.9900},courses:["Football","Indoor Games","Fitness"],district:"Nellore"},
{name:"WaterCare Swimming Pool",skill:"Swimming",rating:4.4,reviews_count:55,address:"Podalakur Road, Nellore, AP",phone:"",email:"",website:"",description:"Swimming training pool with certified coaches.",hours:["Mon–Sat: 5:30 AM – 8 PM"],location:{lat:14.4426,lng:79.9865},courses:["Beginner Swimming","Advanced Swimming","Water Safety"],district:"Nellore"},
{name:"Martial Arts Training School Nellore",skill:"Martial Arts",rating:4.1,reviews_count:40,address:"GT Road, Nellore, AP",phone:"",email:"",website:"",description:"Martial arts and fitness gym combined training center.",hours:["Mon–Sat: 6 AM – 9 PM"],location:{lat:14.4400,lng:79.9850},courses:["Martial Arts","Self-Defense","Fitness"],district:"Nellore"},

// ══════════ NELLORE — FITNESS ══════════
{name:"Yogalayam Nellore",skill:"Yoga",rating:5.0,reviews_count:55,address:"Somasekara Puram, Nellore, AP",phone:"+91 9246434586",email:"",website:"",description:"Daily yoga sessions and beginner-friendly training near RTC Bus Stand.",hours:["Mon–Sat: 5 AM – 8 PM"],location:{lat:14.4426,lng:79.9865},courses:["Daily Yoga","Beginners Yoga","Pranayama"],district:"Nellore"},
{name:"ANANDA Yoga Shala",skill:"Yoga",rating:4.9,reviews_count:45,address:"Mulapet Road, Nellore, AP",phone:"+91 8801505615",email:"",website:"",description:"Traditional yoga and holistic wellness center.",hours:["Mon–Sat: 5 AM – 7 PM"],location:{lat:14.4400,lng:79.9900},courses:["Traditional Yoga","Wellness","Meditation"],district:"Nellore"},
{name:"Future Fitness Gym & Shuttle Complex",skill:"Fitness Training",rating:4.8,reviews_count:100,address:"Mini Bypass Road, Nellore, AP",phone:"+91 7799890404",email:"",website:"https://futurefitnessgymnellore.com/",description:"Modern gym with shuttle courts, cardio, and personal training programs.",hours:["Mon–Sat: 5 AM – 10 PM"],location:{lat:14.4426,lng:79.9865},courses:["Cardio","Strength","Shuttle","Personal Training"],district:"Nellore"},
{name:"Kong Fitness Studio",skill:"Fitness Training",rating:4.9,reviews_count:75,address:"Magunta Layout, Nellore, AP",phone:"+91 7330872240",email:"",website:"",description:"Functional fitness and modern workout programs.",hours:["Mon–Sat: 5 AM – 10 PM"],location:{lat:14.4450,lng:79.9900},courses:["Functional Fitness","Strength","Cardio"],district:"Nellore"},

// ══════════ TIRUPATI — SPORTS ══════════
{name:"SV University Cricket Ground",skill:"Cricket",rating:4.6,reviews_count:50,address:"SV University Campus, Tirupati, AP",phone:"",email:"",website:"https://svuniversity.edu.in",description:"Cricket training at Sri Venkateswara University grounds with university coaching staff.",hours:["Mon–Sat: 5:30 AM – 6 PM"],location:{lat:13.6288,lng:79.4192},courses:["Batting","Bowling","Fielding"],district:"Tirupati"},
{name:"Shaolin Martial Arts Academy Tirupati",skill:"Martial Arts",rating:4.6,reviews_count:45,address:"Tirupati, AP",phone:"+91 98490 56789",email:"",website:"http://www.shaolinsindia.com",description:"Martial arts training with self-defense and competitive programs.",hours:["Mon–Sat: 6 AM – 9 PM"],location:{lat:13.6300,lng:79.4200},courses:["Karate","Self-Defense","Kung Fu"],district:"Tirupati"},

// ══════════ TIRUPATI — FITNESS ══════════
{name:"Eshwari Yoga Mandiram",skill:"Yoga",rating:5.0,reviews_count:80,address:"VV Mahal Road, Tirupati, AP",phone:"+91 9666292029",email:"",website:"",description:"Popular yoga center with traditional therapy and wellness programs.",hours:["Mon–Sat: 5 AM – 8 PM"],location:{lat:13.6288,lng:79.4192},courses:["Traditional Yoga","Yoga Therapy","Pranayama"],district:"Tirupati"},
{name:"Yuj The Yoga Studio",skill:"Yoga",rating:5.0,reviews_count:60,address:"Korramenugunta, Tirupati, AP",phone:"+91 9177263484",email:"",website:"",description:"Yoga therapy, weight loss, and wellness sessions.",hours:["Mon–Sat: 5 AM – 8 PM"],location:{lat:13.6300,lng:79.4200},courses:["Yoga Therapy","Weight Loss Yoga","Wellness"],district:"Tirupati"},
{name:"BBC Bouncers Fitness Gym",skill:"Fitness Training",rating:4.8,reviews_count:90,address:"Karakambadi Road, Tirupati, AP",phone:"+91 9494776969",email:"",website:"",description:"Strength training and bodybuilding gym with expert trainers.",hours:["Mon–Sat: 5 AM – 10 PM"],location:{lat:13.6288,lng:79.4192},courses:["Strength Training","Bodybuilding","Cardio"],district:"Tirupati"},
{name:"Damu Fitness Gym",skill:"Fitness Training",rating:4.9,reviews_count:70,address:"DBR Hospital Road, Tirupati, AP",phone:"+91 9515855477",email:"",website:"",description:"Cardio and strength training with personal coaching.",hours:["Mon–Sat: 5 AM – 10 PM"],location:{lat:13.6250,lng:79.4150},courses:["Cardio","Strength","Personal Training"],district:"Tirupati"},

// ══════════ KURNOOL — SPORTS ══════════
{name:"Kurnool Cricket Academy",skill:"Cricket",rating:4.4,reviews_count:55,address:"Stadium Road, Kurnool, AP",phone:"+91 94400 12345",email:"",website:"",description:"Cricket coaching with professional trainers.",hours:["Mon–Sat: 5:30 AM – 6 PM"],location:{lat:15.8281,lng:78.0373},courses:["Batting","Bowling","Fielding"],district:"Kurnool"},
{name:"Shaolin Martial Arts Academy Kurnool",skill:"Martial Arts",rating:4.5,reviews_count:40,address:"Kurnool, AP",phone:"+91 98490 56789",email:"",website:"http://www.shaolinsindia.com",description:"Martial arts and self-defense training.",hours:["Mon–Sat: 6 AM – 9 PM"],location:{lat:15.8300,lng:78.0400},courses:["Karate","Kung Fu","Self-Defense"],district:"Kurnool"},

// ══════════ KURNOOL — FITNESS ══════════
{name:"Yoga Chaitanya Kurnool",skill:"Yoga",rating:4.9,reviews_count:65,address:"Ashok Nagar, Kurnool, AP",phone:"+91 94407 65432",email:"",website:"https://yogachaitanya.org",description:"Traditional yoga, pranayama & meditation center.",hours:["Mon–Sat: 5 AM – 8 PM"],location:{lat:15.8281,lng:78.0373},courses:["Traditional Yoga","Pranayama","Meditation"],district:"Kurnool"},
{name:"Art of Living Yoga Center Kurnool",skill:"Yoga",rating:4.8,reviews_count:55,address:"N R Peta, Kurnool, AP",phone:"+91 98850 12345",email:"",website:"https://www.artofliving.org/in-en",description:"Sudarshan Kriya, meditation, and stress relief programs.",hours:["Mon–Sat: 5 AM – 8 PM"],location:{lat:15.8260,lng:78.0380},courses:["Sudarshan Kriya","Meditation","Stress Relief"],district:"Kurnool"},
{name:"Muscle Factory Gym Kurnool",skill:"Fitness Training",rating:4.8,reviews_count:70,address:"Gayathri Estate, Kurnool, AP",phone:"+91 90321 11223",email:"",website:"https://musclefactorygym.com",description:"Bodybuilding and strength training facility.",hours:["Mon–Sat: 5 AM – 10 PM"],location:{lat:15.8300,lng:78.0400},courses:["Bodybuilding","Strength Training","Cardio"],district:"Kurnool"},

// ══════════ ANANTAPUR — SPORTS ══════════
{name:"RDT Football Academy Anantapur",skill:"Football",rating:4.7,reviews_count:60,address:"RDT Stadium, Anantapur, AP",phone:"",email:"",website:"https://rdt.org",description:"Football academy supported by Rural Development Trust with professional training.",hours:["Mon–Sat: 5 AM – 7 PM"],location:{lat:14.6819,lng:77.6006},courses:["Football Basics","Advanced Skills","Match Play"],district:"Anantapuramu"},
{name:"Shaolin Martial Arts Academy Anantapur",skill:"Martial Arts",rating:4.6,reviews_count:40,address:"Anantapur, AP",phone:"+91 98490 56789",email:"",website:"http://www.shaolinsindia.com",description:"Martial arts training center with self-defense programs.",hours:["Mon–Sat: 6 AM – 9 PM"],location:{lat:14.6850,lng:77.6050},courses:["Karate","Self-Defense","Kung Fu"],district:"Anantapuramu"},

// ══════════ ANANTAPUR — FITNESS ══════════
{name:"Patanjali Yoga Kendra Anantapur",skill:"Yoga",rating:4.7,reviews_count:55,address:"Ram Nagar, Anantapur, AP",phone:"+91 94915 67890",email:"",website:"https://www.divyayoga.com",description:"Patanjali yoga, pranayama & naturopathy center.",hours:["Mon–Sat: 5 AM – 8 PM"],location:{lat:14.6819,lng:77.6006},courses:["Patanjali Yoga","Pranayama","Naturopathy"],district:"Anantapuramu"},
{name:"Art of Living Center Anantapur",skill:"Yoga",rating:4.8,reviews_count:50,address:"Ashok Nagar, Anantapur, AP",phone:"+91 98850 23456",email:"",website:"https://www.artofliving.org/in-en",description:"Meditation, Sudarshan Kriya, and wellness programs.",hours:["Mon–Sat: 5 AM – 8 PM"],location:{lat:14.6850,lng:77.6050},courses:["Sudarshan Kriya","Meditation","Wellness"],district:"Anantapuramu"},
{name:"Muscle Factory Gym Anantapur",skill:"Fitness Training",rating:4.8,reviews_count:65,address:"Kamalanagar, Anantapur, AP",phone:"+91 90300 99887",email:"",website:"https://musclefactorygym.com",description:"Bodybuilding and weight training facility.",hours:["Mon–Sat: 5 AM – 10 PM"],location:{lat:14.6800,lng:77.5950},courses:["Bodybuilding","Weight Training","Cardio"],district:"Anantapuramu"},

// ══════════ KADAPA — SPORTS ══════════
{name:"AP Sports Authority Cricket Ground Kadapa",skill:"Cricket",rating:4.3,reviews_count:40,address:"Sports Authority Complex, Kadapa, AP",phone:"",email:"",website:"https://sportsauthority.ap.gov.in",description:"State sports authority cricket ground with coaching programs.",hours:["Mon–Sat: 5:30 AM – 6 PM"],location:{lat:14.4673,lng:78.8242},courses:["Batting","Bowling","Fielding"],district:"YSR Kadapa"},
{name:"Shaolin Martial Arts Academy Kadapa",skill:"Martial Arts",rating:4.5,reviews_count:35,address:"Kadapa, AP",phone:"+91 98490 56789",email:"",website:"http://www.shaolinsindia.com",description:"Martial arts training with self-defense and competitive programs.",hours:["Mon–Sat: 6 AM – 9 PM"],location:{lat:14.4700,lng:78.8280},courses:["Karate","Self-Defense","Kung Fu"],district:"YSR Kadapa"},

// ══════════ KADAPA — FITNESS ══════════
{name:"Art Of Living Centre Kadapa",skill:"Yoga",rating:4.7,reviews_count:45,address:"Yerramukkapalli, Kadapa, AP",phone:"+91 08639 305987",email:"",website:"https://www.artofliving.org",description:"Meditation, Sudarshan Kriya & yoga programs.",hours:["Mon–Sat: 5 AM – 8 PM"],location:{lat:14.4673,lng:78.8242},courses:["Sudarshan Kriya","Meditation","Yoga"],district:"YSR Kadapa"},
{name:"Universal Gym Kadapa",skill:"Fitness Training",rating:4.5,reviews_count:55,address:"Balaji Nagar, Kadapa, AP",phone:"+91 88856 88576",email:"",website:"",description:"Strength training and cardio equipment gym.",hours:["Mon–Sat: 5 AM – 10 PM"],location:{lat:14.4700,lng:78.8280},courses:["Strength Training","Cardio","Weight Training"],district:"YSR Kadapa"},
{name:"Rainbow Fitness Gym Kadapa",skill:"Fitness Training",rating:4.3,reviews_count:50,address:"Ganagapeta, Kadapa, AP",phone:"+91 99499 55453",email:"",website:"",description:"Popular local gym with daily workouts.",hours:["Mon–Sat: 5 AM – 10 PM"],location:{lat:14.4650,lng:78.8200},courses:["Workouts","Cardio","Fitness"],district:"YSR Kadapa"},

// ══════════ RAJAHMUNDRY — FITNESS ══════════
{name:"Art of Living Center Rajahmundry",skill:"Yoga",rating:4.7,reviews_count:55,address:"Danavaipeta, Rajahmundry, AP",phone:"",email:"",website:"https://www.artofliving.org/in-en",description:"Meditation, Sudarshan Kriya & stress relief programs.",hours:["Mon–Sat: 5 AM – 8 PM"],location:{lat:17.0005,lng:81.8040},courses:["Sudarshan Kriya","Meditation","Stress Relief"],district:"East Godavari"},
{name:"Patanjali Yoga Samiti Rajahmundry",skill:"Yoga",rating:4.6,reviews_count:50,address:"Tilak Road, Rajahmundry, AP",phone:"",email:"",website:"https://www.divyayoga.com",description:"Traditional yoga, pranayama & ayurveda center.",hours:["Mon–Sat: 5 AM – 8 PM"],location:{lat:17.0020,lng:81.8050},courses:["Traditional Yoga","Pranayama","Ayurveda"],district:"East Godavari"},

// ══════════ ELURU — SPORTS ══════════
{name:"ANM Cricket Academy",skill:"Cricket",rating:5.0,reviews_count:55,address:"Vanguru, Eluru, AP",phone:"+91 95407 33406",email:"",website:"http://anmcricketacademy.com/",description:"Professional cricket coaching with certified trainers.",hours:["Mon–Sat: 5:30 AM – 6 PM"],location:{lat:16.7107,lng:81.0952},courses:["Batting","Bowling","Fielding","Match Play"],district:"Eluru"},
{name:"Eluru Cricket Turf",skill:"Cricket",rating:4.8,reviews_count:45,address:"Komadavole Rural, Eluru, AP",phone:"+91 79897 14518",email:"",website:"",description:"Cricket turf with net practice and coaching.",hours:["Mon–Sat: 5 AM – 7 PM"],location:{lat:16.7150,lng:81.0900},courses:["Net Practice","Batting","Bowling"],district:"Eluru"},
{name:"Seiko Shotokan Karate Organisation",skill:"Martial Arts",rating:4.9,reviews_count:50,address:"Narasimharao Pet, Eluru, AP",phone:"+91 94402 19533",email:"",website:"https://ssk-do.com/",description:"Advanced karate training with international standards.",hours:["Mon–Sat: 6 AM – 8 PM"],location:{lat:16.7120,lng:81.0980},courses:["Shotokan Karate","Self-Defense","Tournament Prep"],district:"Eluru"},
{name:"Shakeel's Martial Karate Institute",skill:"Martial Arts",rating:4.5,reviews_count:40,address:"Powerpet, Eluru, AP",phone:"+91 98488 27863",email:"",website:"",description:"Karate training for children and adults.",hours:["Mon–Sat: 6 AM – 8 PM"],location:{lat:16.7107,lng:81.0952},courses:["Karate","Self-Defense"],district:"Eluru"},

// ══════════ ELURU — FITNESS ══════════
{name:"SS Swimming Pool Satrampadu",skill:"Swimming",rating:4.9,reviews_count:50,address:"Vatluru, Eluru, AP",phone:"",email:"",website:"",description:"Swimming pool with coaching for all levels.",hours:["Mon–Sat: 5:30 AM – 8 PM"],location:{lat:16.7107,lng:81.0952},courses:["Beginner Swimming","Advanced Swimming"],district:"Eluru"},

// ══════════ VIZIANAGARAM — SPORTS ══════════
{name:"Game On VZM",skill:"Football",rating:4.7,reviews_count:55,address:"Dharmapuri, Vizianagaram, AP",phone:"+91 94912 33543",email:"",website:"",description:"Sports playground with football training and coaching.",hours:["Mon–Sat: 5 AM – 8 PM"],location:{lat:18.1067,lng:83.3956},courses:["Football Basics","Advanced Skills"],district:"Vizianagaram"},
{name:"Kenyu Ryu Karate & Kick Boxing",skill:"Martial Arts",rating:4.9,reviews_count:45,address:"Thotapalem, Vizianagaram, AP",phone:"+91 96660 00325",email:"",website:"",description:"Karate and kickboxing classes with experienced instructors.",hours:["Mon–Sat: 6 AM – 8 PM"],location:{lat:18.1100,lng:83.4000},courses:["Karate","Kickboxing","Self-Defense"],district:"Vizianagaram"},
{name:"Sekhar Taekwondo Academy",skill:"Martial Arts",rating:5.0,reviews_count:35,address:"Santha Pet, Vizianagaram, AP",phone:"+91 63047 70055",email:"",website:"",description:"Taekwondo training with championship-level coaching.",hours:["Mon–Sat: 6 AM – 8 PM"],location:{lat:18.1050,lng:83.3900},courses:["Taekwondo","Competition Training"],district:"Vizianagaram"},

// ══════════ VIZIANAGARAM — FITNESS ══════════
{name:"Aqua Sports Complex Vizianagaram",skill:"Swimming",rating:4.6,reviews_count:40,address:"Cantonment, Vizianagaram, AP",phone:"",email:"",website:"",description:"Outdoor swimming pool with training programs.",hours:["Mon–Sat: 5:30 AM – 7 PM"],location:{lat:18.1067,lng:83.3956},courses:["Swimming","Water Safety"],district:"Vizianagaram"},

// ══════════ SRIKAKULAM — SPORTS ══════════
{name:"District Sports Authority Cricket Ground Srikakulam",skill:"Cricket",rating:4.3,reviews_count:35,address:"Sports Complex, Srikakulam, AP",phone:"",email:"",website:"https://sportsauthority.ap.gov.in",description:"District sports authority cricket coaching.",hours:["Mon–Sat: 5:30 AM – 6 PM"],location:{lat:18.2949,lng:83.8938},courses:["Batting","Bowling","Fielding"],district:"Srikakulam"},
{name:"Shaolin Martial Arts Academy Srikakulam",skill:"Martial Arts",rating:4.5,reviews_count:30,address:"Srikakulam, AP",phone:"+91 98490 56789",email:"",website:"http://www.shaolinsindia.com",description:"Martial arts and self-defense training.",hours:["Mon–Sat: 6 AM – 9 PM"],location:{lat:18.2960,lng:83.8950},courses:["Karate","Self-Defense","Kung Fu"],district:"Srikakulam"},

// ══════════ SRIKAKULAM — FITNESS ══════════
{name:"Yoga City Charitable Trust",skill:"Yoga",rating:3.4,reviews_count:40,address:"Srikakulam, AP",phone:"",email:"",website:"https://www.sulekha.com/yoga-classes-at-home/srikakulam",description:"Home yoga training & therapy-based yoga.",hours:["Mon–Sat: 5 AM – 8 PM"],location:{lat:18.2949,lng:83.8938},courses:["Home Yoga","Therapy Yoga","Pranayama"],district:"Srikakulam"},
{name:"Heartfulness Meditation Center Srikakulam",skill:"Yoga",rating:5.0,reviews_count:35,address:"A.P.H.B Colony, Srikakulam, AP",phone:"+91 94419 67457",email:"",website:"https://heartfulness.org",description:"Meditation + Raja Yoga programs.",hours:["Mon–Sat: 5 AM – 8 PM"],location:{lat:18.2960,lng:83.8950},courses:["Raja Yoga","Meditation","Wellness"],district:"Srikakulam"},
{name:"Flex Health Gym",skill:"Fitness Training",rating:4.5,reviews_count:279,address:"Women's College Road, Srikakulam, AP",phone:"",email:"",website:"",description:"One of the most popular gyms in Srikakulam.",hours:["Mon–Sat: 5 AM – 10 PM"],location:{lat:18.2949,lng:83.8938},courses:["Strength Training","Cardio","Fitness"],district:"Srikakulam"},
{name:"Gopal Fitness",skill:"Fitness Training",rating:4.8,reviews_count:45,address:"Zilla Parishad Road, Srikakulam, AP",phone:"+91 98662 20334",email:"",website:"",description:"Well-rated local gym.",hours:["Mon–Sat: 5 AM – 10 PM"],location:{lat:18.2970,lng:83.8960},courses:["Strength","Cardio","Weight Training"],district:"Srikakulam"},

// ══════════ CHITTOOR — SPORTS ══════════
{name:"District Sports Authority Cricket Ground Chittoor",skill:"Cricket",rating:4.3,reviews_count:35,address:"Sports Complex, Chittoor, AP",phone:"",email:"",website:"https://sportsauthority.ap.gov.in",description:"District sports cricket coaching facility.",hours:["Mon–Sat: 5:30 AM – 6 PM"],location:{lat:13.2172,lng:79.1003},courses:["Batting","Bowling","Fielding"],district:"Chittoor"},
{name:"Shaolin Martial Arts Academy Chittoor",skill:"Martial Arts",rating:4.5,reviews_count:30,address:"Chittoor, AP",phone:"+91 98490 56789",email:"",website:"http://www.shaolinsindia.com",description:"Martial arts training with self-defense programs.",hours:["Mon–Sat: 6 AM – 9 PM"],location:{lat:13.2200,lng:79.1050},courses:["Karate","Self-Defense","Kung Fu"],district:"Chittoor"},

// ══════════ ONGOLE — SPORTS & FITNESS ══════════
{name:"Ongole Cricket Academy",skill:"Cricket",rating:4.7,reviews_count:290,address:"Stadium Road, Ongole, AP 523001",phone:"+91 99876 54321",email:"ongolecricket@gmail.com",website:"https://ongolecricketacademy.com",description:"BCCI-affiliated cricket academy with professional coaching. Net practice, bowling machines, and video analysis.",hours:["Mon–Sat: 5:30 AM – 7 PM"],location:{lat:15.5050,lng:80.0475},courses:["Batting","Bowling & Fielding","Wicket-keeping","Match Strategy"],district:"Ongole"},
{name:"Prakasam Football Academy",skill:"Football",rating:4.5,reviews_count:142,address:"Bypass Road, Ongole, AP 523002",phone:"+91 91234 56789",email:"prakasamfootball@gmail.com",website:"https://prakasamfa.com",description:"AIFF-recognized football academy with FIFA-trained coaches for all positions.",hours:["Mon–Sat: 5 AM – 7 PM"],location:{lat:15.5095,lng:80.0490},courses:["Football Basics","Advanced Skills","Goalkeeper Training","Tactical Play"],district:"Ongole"},
{name:"Aqua Splash Swimming Academy",skill:"Swimming",rating:4.6,reviews_count:168,address:"Chimakurthy Road, Ongole, AP 523001",phone:"+91 92109 87654",email:"aquasplash.ongole@gmail.com",website:"https://aquasplashswim.com",description:"Olympic-size pool with temperature control. Learn all strokes and competitive swimming.",hours:["Mon–Sat: 5:30 AM – 8 PM"],location:{lat:15.5040,lng:80.0420},courses:["Beginner Swimming","Competitive Swimming","Water Safety","Dive Training"],district:"Ongole"},
{name:"Dragon Warrior Martial Arts",skill:"Martial Arts",rating:4.8,reviews_count:130,address:"Old Club Road, Ongole, AP 523001",phone:"+91 93456 78012",email:"dragonwarrior.ma@gmail.com",website:"https://dragonwarriormartialarts.in",description:"Training in Karate, Taekwondo, Kung Fu, and Judo. Self-defense programs for women and children.",hours:["Mon–Sat: 6 AM – 9 PM"],location:{lat:15.5068,lng:80.0450},courses:["Karate","Taekwondo","Kung Fu","Self-Defense"],district:"Ongole"},
{name:"Shanti Yoga Ashram",skill:"Yoga",rating:4.9,reviews_count:235,address:"Venkateswara Nagar, Ongole, AP 523001",phone:"+91 96789 01234",email:"shantiyoga.ongole@gmail.com",website:"https://shantiyogaashram.org",description:"Authentic yoga training center with Hatha Yoga, Ashtanga Yoga, Pranayama, and therapeutic yoga.",hours:["Mon–Sun: 5 AM – 9 PM"],location:{lat:15.5060,lng:80.0440},courses:["Hatha Yoga","Ashtanga Yoga","Pranayama","Yoga Teacher Training"],district:"Ongole"},
{name:"Inner Peace Meditation Centre",skill:"Meditation",rating:4.7,reviews_count:98,address:"Bharathi Nagar, Ongole, AP 523001",phone:"+91 97654 32109",email:"innerpeace.ongole@gmail.com",website:"https://innerpeacemeditation.in",description:"Vipassana, mindfulness, and transcendental meditation. Weekend silent retreats available.",hours:["Mon–Sun: 5 AM – 8 PM"],location:{lat:15.5055,lng:80.0460},courses:["Vipassana Meditation","Mindfulness","Transcendental Meditation"],district:"Ongole"},
{name:"Iron Forge Fitness Studio",skill:"Fitness Training",rating:4.6,reviews_count:156,address:"Kurnool Road, Ongole, AP 523002",phone:"+91 98901 23456",email:"ironforge.fitness@gmail.com",website:"https://ironforgefitness.com",description:"State-of-the-art gym with CrossFit, HIIT, strength training, and diet counseling.",hours:["Mon–Sat: 5 AM – 10 PM"],location:{lat:15.5078,lng:80.0535},courses:["CrossFit","HIIT Training","Strength Training","Weight Loss"],district:"Ongole"}
];
module.exports = { SPORTS_FITNESS_ACADEMIES };